// Generated by Framer (beb597f)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const serializationHash = "framer-AXP5o";
const variantClassNames = { H0fTQUhl9: "framer-v-1hsyf8u" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const iIiG4RFTv = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, width, ...props }) => {
  return { ...props, iIiG4RFTv: link ?? props.iIiG4RFTv };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, iIiG4RFTv, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "H0fTQUhl9",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: iIiG4RFTv,
          motionChild: true,
          nodeId: "H0fTQUhl9",
          scopeId: "bWCjYCsf5",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsx(Image, {
            ...restProps,
            ...gestureHandlers,
            as: "a",
            background: {
              alt: "",
              fit: "fit",
              loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
              pixelHeight: 287,
              pixelWidth: 1130,
              positionX: "center",
              positionY: "center",
              sizes: componentViewport?.width || "100vw",
              src: "https://framerusercontent.com/images/5KOxwa8bkim9ChFC7WtaVXsr90A.png?width=1130&height=287",
              srcSet:
                "https://framerusercontent.com/images/5KOxwa8bkim9ChFC7WtaVXsr90A.png?scale-down-to=512&width=1130&height=287 512w,https://framerusercontent.com/images/5KOxwa8bkim9ChFC7WtaVXsr90A.png?scale-down-to=1024&width=1130&height=287 1024w,https://framerusercontent.com/images/5KOxwa8bkim9ChFC7WtaVXsr90A.png?width=1130&height=287 1130w",
            },
            className: `${cx(
              scopingClassNames,
              "framer-1hsyf8u",
              className,
              classNames
            )} framer-un9v3z`,
            "data-framer-name": "Default",
            layoutDependency: layoutDependency,
            layoutId: "H0fTQUhl9",
            ref: refBinding,
            style: { ...style },
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-AXP5o.framer-un9v3z, .framer-AXP5o .framer-un9v3z { display: block; }",
  ".framer-AXP5o.framer-1hsyf8u { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 74px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 197px; will-change: var(--framer-will-change-filter-override, filter); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 74
 * @framerIntrinsicWidth 197
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"iIiG4RFTv":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerbWCjYCsf5 = withCSS(Component, css, "framer-AXP5o");
export default FramerbWCjYCsf5;
FramerbWCjYCsf5.displayName = "Logo";
FramerbWCjYCsf5.defaultProps = { height: 74, width: 197 };
addPropertyControls(FramerbWCjYCsf5, {
  iIiG4RFTv: { title: "Link", type: ControlType.Link },
});
addFonts(FramerbWCjYCsf5, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerbWCjYCsf5",
      slots: [],
      annotations: {
        framerVariables: '{"iIiG4RFTv":"link"}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "74",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerIntrinsicWidth: "197",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./bWCjYCsf5.map
