// Generated by Framer (9f1494d)
import { fontStore } from "framer";
fontStore.loadFonts(["GF;Luckiest Guy-regular"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Luckiest Guy",
        openType: true,
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/luckiestguy/v23/_gP_1RrxsjcxVyin9l9n_j2RT9R3qDpraA.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  ".framer-my1FT .framer-styles-preset-1gou2ux:not(.rich-text-wrapper), .framer-my1FT .framer-styles-preset-1gou2ux.rich-text-wrapper p { --framer-font-family: \"Luckiest Guy\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, #100c18); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }",
];
export const className = "framer-my1FT";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
