// Generated by Framer (beb597f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/qFOisoTaPt79EohwJFUC/FDVbzDHjh8oETI4INdbd/Kxww_nbP7.js";
import CopyButton from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/q3Zez3HKRUYhMy7ddJ8h/8lgpnbvGon19OOyPP93j/P4JARSZGA.js";
const CopyButtonFonts = getFonts(CopyButton);
const cycleOrder = ["gDEvVG0kV", "RciaDBxO8"];
const serializationHash = "framer-1nUBm";
const variantClassNames = {
  gDEvVG0kV: "framer-v-43mot2",
  RciaDBxO8: "framer-v-16a7ap8",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "gDEvVG0kV", Phone: "RciaDBxO8" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "gDEvVG0kV",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "gDEvVG0kV",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-43mot2",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "gDEvVG0kV",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { RciaDBxO8: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-wmm42a",
              "data-framer-name": "BG + Border",
              layoutDependency: layoutDependency,
              layoutId: "t8SsuNJuy",
              children: [
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "Border",
                    fit: "fill",
                    intrinsicHeight: 107,
                    intrinsicWidth: 665,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0
                    ),
                    pixelHeight: 107,
                    pixelWidth: 665,
                    sizes: componentViewport?.width || "100vw",
                    src: "https://framerusercontent.com/images/rcxpbCnfSS2AWpwueivkPTEdhw.svg?width=665&height=107",
                    srcSet:
                      "https://framerusercontent.com/images/rcxpbCnfSS2AWpwueivkPTEdhw.svg?scale-down-to=512&width=665&height=107 512w,https://framerusercontent.com/images/rcxpbCnfSS2AWpwueivkPTEdhw.svg?width=665&height=107 665w",
                  },
                  className: "framer-67bifj",
                  "data-framer-name": "Border",
                  layoutDependency: layoutDependency,
                  layoutId: "wQ6xq_UBt",
                  ...addPropertyOverrides(
                    {
                      RciaDBxO8: {
                        background: {
                          alt: "Border",
                          fit: "fill",
                          intrinsicHeight: 107,
                          intrinsicWidth: 665,
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 0 + 0
                          ),
                          pixelHeight: 158,
                          pixelWidth: 364,
                          sizes: componentViewport?.width || "100vw",
                          src: "https://framerusercontent.com/images/u1MAw8jD8UAQi4iKvrimyCWOJE.svg?width=364&height=158",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "BG",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) +
                        0 +
                        (10 +
                          ((componentViewport?.height || 106) -
                            0 -
                            20 -
                            ((componentViewport?.height || 106) - 0 - 20) * 1) /
                            2)
                    ),
                    pixelHeight: 87,
                    pixelWidth: 645,
                    sizes: `max(${
                      componentViewport?.width || "100vw"
                    } - 20px, 1px)`,
                    src: "https://framerusercontent.com/images/viXzUrVSvggJuuQdNh2zJoh7wtI.svg?width=645&height=87",
                    srcSet:
                      "https://framerusercontent.com/images/viXzUrVSvggJuuQdNh2zJoh7wtI.svg?scale-down-to=512&width=645&height=87 512w,https://framerusercontent.com/images/viXzUrVSvggJuuQdNh2zJoh7wtI.svg?width=645&height=87 645w",
                  },
                  className: "framer-1lnbh2e",
                  "data-framer-name": "BG",
                  layoutDependency: layoutDependency,
                  layoutId: "aq8KStA2e",
                  ...addPropertyOverrides(
                    {
                      RciaDBxO8: {
                        background: {
                          alt: "BG",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              0 +
                              (10 +
                                ((componentViewport?.height || 160) -
                                  0 -
                                  20 -
                                  ((componentViewport?.height || 160) -
                                    0 -
                                    20) *
                                    1) /
                                  2)
                          ),
                          pixelHeight: 143,
                          pixelWidth: 353,
                          sizes: `max(${
                            componentViewport?.width || "100vw"
                          } - 20px, 1px)`,
                          src: "https://framerusercontent.com/images/KHTYV3oWTVQONes1KfQZjemcw.svg?width=353&height=143",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-ysjcsl",
              "data-framer-name": "Content",
              layoutDependency: layoutDependency,
              layoutId: "ff1kte1zn",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1q85jf4",
                    "data-styles-preset": "Kxww_nbP7",
                    children: "0xComingSoon",
                  }),
                }),
                className: "framer-dd0ufq",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "o4gzR9ZLY",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    RciaDBxO8: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-1q85jf4",
                          "data-styles-preset": "Kxww_nbP7",
                          style: { "--framer-text-alignment": "center" },
                          children:
                            "0xComingSoon",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 23,
              y:
                (componentViewport?.y || 0) +
                (0 + ((componentViewport?.height || 106) - 0 - 23) / 2),
              ...addPropertyOverrides(
                {
                  RciaDBxO8: {
                    y:
                      (componentViewport?.y || 0) +
                      35 +
                      (((componentViewport?.height || 160) - 70 - 151) / 2 +
                        108 +
                        20),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-mk5wqt-container",
                layoutDependency: layoutDependency,
                layoutId: "hjHl79sgD-container",
                nodeId: "hjHl79sgD",
                rendersWithMotion: true,
                scopeId: "tr_lsFFF0",
                children: /*#__PURE__*/ _jsx(CopyButton, {
                  DTUIEisSq: "0xComingSoon",
                  height: "100%",
                  id: "hjHl79sgD",
                  layoutId: "hjHl79sgD",
                  variant: "YMtl12FbF",
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-1nUBm.framer-1osz92z, .framer-1nUBm .framer-1osz92z { display: block; }",
  ".framer-1nUBm.framer-43mot2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: 106px; justify-content: space-between; overflow: visible; padding: 0px 35px 0px 35px; position: relative; width: 661px; }",
  ".framer-1nUBm .framer-wmm42a { -webkit-user-select: none; align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: visible; padding: 10px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; }",
  ".framer-1nUBm .framer-67bifj { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
  ".framer-1nUBm .framer-1lnbh2e { flex: 1 0 0px; height: 100%; overflow: visible; position: relative; width: 1px; }",
  ".framer-1nUBm .framer-ysjcsl { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 82%; overflow: visible; padding: 0px; position: relative; user-select: none; width: 1px; }",
  ".framer-1nUBm .framer-dd0ufq { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-1nUBm .framer-mk5wqt-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-1nUBm.framer-v-16a7ap8.framer-43mot2 { aspect-ratio: 2.3125 / 1; flex-direction: column; gap: 20px; height: var(--framer-aspect-ratio-supported, 160px); justify-content: center; padding: 35px 20px 35px 20px; width: 370px; }",
  ".framer-1nUBm.framer-v-16a7ap8 .framer-ysjcsl { flex: none; max-width: 100%; width: 100%; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 106
 * @framerIntrinsicWidth 661
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"RciaDBxO8":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framertr_lsFFF0 = withCSS(Component, css, "framer-1nUBm");
export default Framertr_lsFFF0;
Framertr_lsFFF0.displayName = "Copy Clipboard";
Framertr_lsFFF0.defaultProps = { height: 106, width: 661 };
addPropertyControls(Framertr_lsFFF0, {
  variant: {
    options: ["gDEvVG0kV", "RciaDBxO8"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  Framertr_lsFFF0,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...CopyButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framertr_lsFFF0",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "106",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"RciaDBxO8":{"layout":["fixed","fixed"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "661",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./tr_lsFFF0.map
