// Generated by Framer (beb597f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Logo from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/mwtuTDjLRWmCnXFSPqXH/QLXg5cs3CZFaZkZhiVog/bWCjYCsf5.js";
import Button from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/6iQnPT6QWpALdNioZ1Vc/vuWMO7Mf7xEXVds3Cnze/Dc_z1yLfb.js";
import SocialLink from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/gj09UedkVkDb0Xzt0TXm/uwAlzFGMuW8AlMdscPL9/ZrbdnhbfF.js";
const LogoFonts = getFonts(Logo);
const SocialLinkFonts = getFonts(SocialLink);
const ButtonFonts = getFonts(Button);
const cycleOrder = ["dKLcsb4Hw", "RlvGJyhCo"];
const serializationHash = "framer-ffouG";
const variantClassNames = {
  dKLcsb4Hw: "framer-v-9ed6uy",
  RlvGJyhCo: "framer-v-j1fg6p",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const qUsgEym5f = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "dKLcsb4Hw", Phone: "RlvGJyhCo" };
const getProps = ({ height, id, logoLink, width, ...props }) => {
  return {
    ...props,
    qUsgEym5f: logoLink ?? props.qUsgEym5f,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "dKLcsb4Hw",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, qUsgEym5f, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "dKLcsb4Hw",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "RlvGJyhCo") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.header, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-9ed6uy",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "dKLcsb4Hw",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { RlvGJyhCo: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-14davsc",
            "data-border": true,
            "data-framer-name": "Container",
            layoutDependency: layoutDependency,
            layoutId: "gDW1YFrDM",
            style: {
              "--border-bottom-width": "2px",
              "--border-color":
                "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
              "--border-left-width": "2px",
              "--border-right-width": "2px",
              "--border-style": "solid",
              "--border-top-width": "2px",
              backgroundColor:
                "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
              borderBottomLeftRadius: 16,
              borderBottomRightRadius: 16,
              borderTopLeftRadius: 16,
              borderTopRightRadius: 16,
              boxShadow: "0px 4px 0px 0px rgb(0, 0, 0)",
            },
            children: [
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                height: 74,
                y:
                  (componentViewport?.y || 0) +
                  20 +
                  (((componentViewport?.height || 150) - 40 - 110) / 2 +
                    0 +
                    0) +
                  18,
                ...addPropertyOverrides(
                  {
                    RlvGJyhCo: {
                      height: 45,
                      width: "170px",
                      y:
                        (componentViewport?.y || 0) +
                        20 +
                        (((componentViewport?.height || 108) - 40 - 14) / 2 +
                          0 +
                          0) +
                        -15.5,
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-doy5fl-container",
                  layoutDependency: layoutDependency,
                  layoutId: "RNRpTp3DP-container",
                  nodeId: "RNRpTp3DP",
                  rendersWithMotion: true,
                  scopeId: "xvq9ojUUg",
                  children: /*#__PURE__*/ _jsx(Logo, {
                    height: "100%",
                    id: "RNRpTp3DP",
                    iIiG4RFTv: qUsgEym5f,
                    layoutId: "RNRpTp3DP",
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        RlvGJyhCo: { style: { height: "100%", width: "100%" } },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-14zj003",
                "data-framer-name": "Content",
                layoutDependency: layoutDependency,
                layoutId: "fSoXNsJb0",
                children: [
                  isDisplayed() &&
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-1rblt4m",
                      "data-framer-name": "Socials",
                      layoutDependency: layoutDependency,
                      layoutId: "YXp1vqWMQ",
                      children: [
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 46,
                          y:
                            (componentViewport?.y || 0) +
                            20 +
                            (((componentViewport?.height || 150) - 40 - 110) /
                              2 +
                              0 +
                              0) +
                            29 +
                            3 +
                            0,
                          children: /*#__PURE__*/ _jsx(
                            SmartComponentScopedContainer,
                            {
                              className: "framer-119x9hs-container",
                              layoutDependency: layoutDependency,
                              layoutId: "NkIrdbuDE-container",
                              nodeId: "NkIrdbuDE",
                              rendersWithMotion: true,
                              scopeId: "xvq9ojUUg",
                              children: /*#__PURE__*/ _jsx(SocialLink, {
                                gR9_gy1KR: "https://t.me/NOOBonEther",
                                height: "100%",
                                id: "NkIrdbuDE",
                                layoutId: "NkIrdbuDE",
                                variant: "x1uW2jaoq",
                                width: "100%",
                              }),
                            }
                          ),
                        }),
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 46,
                          y:
                            (componentViewport?.y || 0) +
                            20 +
                            (((componentViewport?.height || 150) - 40 - 110) /
                              2 +
                              0 +
                              0) +
                            29 +
                            3 +
                            0,
                          children: /*#__PURE__*/ _jsx(
                            SmartComponentScopedContainer,
                            {
                              className: "framer-i9ztsg-container",
                              layoutDependency: layoutDependency,
                              layoutId: "d8siCRjXy-container",
                              nodeId: "d8siCRjXy",
                              rendersWithMotion: true,
                              scopeId: "xvq9ojUUg",
                              style: { rotate: 5 },
                              children: /*#__PURE__*/ _jsx(SocialLink, {
                                gR9_gy1KR: "https://x.com/NoobonEther",
                                height: "100%",
                                id: "d8siCRjXy",
                                layoutId: "d8siCRjXy",
                                variant: "OL0h8sJcY",
                                width: "100%",
                              }),
                            }
                          ),
                        }),
                      ],
                    }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 52,
                    y:
                      (componentViewport?.y || 0) +
                      20 +
                      (((componentViewport?.height || 150) - 40 - 110) / 2 +
                        0 +
                        0) +
                      29 +
                      0,
                    ...addPropertyOverrides(
                      {
                        RlvGJyhCo: {
                          y:
                            (componentViewport?.y || 0) +
                            20 +
                            (((componentViewport?.height || 108) - 40 - 14) /
                              2 +
                              0 +
                              0) +
                            7 +
                            -0.3008,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-icu6t8-container",
                        layoutDependency: layoutDependency,
                        layoutId: "jxubJJiEg-container",
                        nodeId: "jxubJJiEg",
                        rendersWithMotion: true,
                        scopeId: "xvq9ojUUg",
                        children: /*#__PURE__*/ _jsx(Button, {
                          height: "100%",
                          id: "jxubJJiEg",
                          layoutId: "jxubJJiEg",
                          MKPg9WbcL: "Buy now",
                          QUXmHzKkq: false,
                          variant: "u9cHE4zsd",
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ffouG.framer-70nocp, .framer-ffouG .framer-70nocp { display: block; }",
  ".framer-ffouG.framer-9ed6uy { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 30px 20px 30px; position: relative; width: 1200px; }",
  ".framer-ffouG .framer-14davsc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1170px; overflow: hidden; padding: 18px 24px 18px 24px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-ffouG .framer-doy5fl-container { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; width: auto; }",
  ".framer-ffouG .framer-14zj003 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-ffouG .framer-1rblt4m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ffouG .framer-119x9hs-container, .framer-ffouG .framer-i9ztsg-container, .framer-ffouG .framer-icu6t8-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-ffouG.framer-v-j1fg6p.framer-9ed6uy { padding: 20px; width: 390px; }",
  ".framer-ffouG.framer-v-j1fg6p .framer-14davsc { padding: 7px 24px 7px 24px; }",
  ".framer-ffouG.framer-v-j1fg6p .framer-doy5fl-container { height: 45px; left: 4px; position: absolute; top: calc(50.00000000000002% - 45px / 2); width: 170px; z-index: 1; }",
  ".framer-ffouG.framer-v-j1fg6p .framer-14zj003 { min-height: 54px; }",
  ".framer-ffouG.framer-v-j1fg6p .framer-icu6t8-container { position: absolute; right: -20px; top: 0px; z-index: 1; }",
  '.framer-ffouG[data-border="true"]::after, .framer-ffouG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 150
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"RlvGJyhCo":{"layout":["fixed","auto"]}}}
 * @framerVariables {"qUsgEym5f":"logoLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerxvq9ojUUg = withCSS(Component, css, "framer-ffouG");
export default Framerxvq9ojUUg;
Framerxvq9ojUUg.displayName = "Header";
Framerxvq9ojUUg.defaultProps = { height: 150, width: 1200 };
addPropertyControls(Framerxvq9ojUUg, {
  variant: {
    options: ["dKLcsb4Hw", "RlvGJyhCo"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  qUsgEym5f: { title: "Logo Link", type: ControlType.Link },
});
addFonts(
  Framerxvq9ojUUg,
  [
    { explicitInter: true, fonts: [] },
    ...LogoFonts,
    ...SocialLinkFonts,
    ...ButtonFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerxvq9ojUUg",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"RlvGJyhCo":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "1200",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "150",
        framerVariables: '{"qUsgEym5f":"logoLink"}',
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./xvq9ojUUg.map
