// Generated by Framer (beb597f)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = {
  jNT1niBTh: { hover: true },
  OL0h8sJcY: { hover: true },
  x1uW2jaoq: { hover: true },
};
const cycleOrder = ["x1uW2jaoq", "OL0h8sJcY", "jNT1niBTh"];
const serializationHash = "framer-Xi8JP";
const variantClassNames = {
  jNT1niBTh: "framer-v-19g2rw1",
  OL0h8sJcY: "framer-v-hd81jr",
  x1uW2jaoq: "framer-v-uka4gs",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const gR9_gy1KR = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Discord: "jNT1niBTh",
  Telegram: "x1uW2jaoq",
  X: "OL0h8sJcY",
};
const getProps = ({ height, id, link, width, ...props }) => {
  return {
    ...props,
    gR9_gy1KR: link ?? props.gR9_gy1KR,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "x1uW2jaoq",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, gR9_gy1KR, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "x1uW2jaoq",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: gR9_gy1KR,
          motionChild: true,
          nodeId: "x1uW2jaoq",
          openInNewTab: true,
          scopeId: "ZrbdnhbfF",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-uka4gs",
              className,
              classNames
            )} framer-6j1x0h`,
            "data-border": true,
            "data-framer-name": "Telegram",
            layoutDependency: layoutDependency,
            layoutId: "x1uW2jaoq",
            ref: refBinding,
            style: {
              "--border-bottom-width": "1.5px",
              "--border-color":
                "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
              "--border-left-width": "1.5px",
              "--border-right-width": "1.5px",
              "--border-style": "solid",
              "--border-top-width": "1.5px",
              backgroundColor:
                "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
              borderBottomLeftRadius: 5,
              borderBottomRightRadius: 5,
              borderTopLeftRadius: 5,
              borderTopRightRadius: 5,
              boxShadow:
                "2.23px 2.23px 0px 0px var(--token-5cbf4025-57b6-40d6-a771-ea8ef74cd640, rgba(0, 0, 0, 0.3))",
              ...style,
            },
            variants: {
              "jNT1niBTh-hover": {
                backgroundColor:
                  "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
              },
              "OL0h8sJcY-hover": {
                backgroundColor:
                  "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
              },
              "x1uW2jaoq-hover": {
                backgroundColor:
                  "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
              },
            },
            ...addPropertyOverrides(
              {
                "jNT1niBTh-hover": { "data-framer-name": undefined },
                "OL0h8sJcY-hover": { "data-framer-name": undefined },
                "x1uW2jaoq-hover": { "data-framer-name": undefined },
                jNT1niBTh: { "data-framer-name": "Discord" },
                OL0h8sJcY: { "data-framer-name": "X" },
              },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-t4ypgj",
              "data-framer-name": "Icon",
              layoutDependency: layoutDependency,
              layoutId: "tCpRXQWn9",
              style: {
                backgroundColor:
                  "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                mask: "url('https://framerusercontent.com/images/3vGJ4DSXkx9xl1WNstqbxUVGA.svg?width=26&height=22') alpha no-repeat center / cover add",
                WebkitMask:
                  "url('https://framerusercontent.com/images/3vGJ4DSXkx9xl1WNstqbxUVGA.svg?width=26&height=22') alpha no-repeat center / cover add",
              },
              variants: {
                "jNT1niBTh-hover": {
                  backgroundColor:
                    "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                },
                "OL0h8sJcY-hover": {
                  backgroundColor:
                    "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                },
                "x1uW2jaoq-hover": {
                  backgroundColor:
                    "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                },
                jNT1niBTh: {
                  mask: "url('https://framerusercontent.com/images/9Sojhak6ec77ENCrIdfyQ0Jy5k8.svg?width=252&height=300') alpha no-repeat center / contain add",
                  WebkitMask:
                    "url('https://framerusercontent.com/images/9Sojhak6ec77ENCrIdfyQ0Jy5k8.svg?width=252&height=300') alpha no-repeat center / contain add",
                },
                OL0h8sJcY: {
                  mask: "url('https://framerusercontent.com/images/GdenteveVs7WV8lOO1fqthhfmjM.svg?width=20&height=19') alpha no-repeat center / cover add",
                  WebkitMask:
                    "url('https://framerusercontent.com/images/GdenteveVs7WV8lOO1fqthhfmjM.svg?width=20&height=19') alpha no-repeat center / cover add",
                },
              },
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Xi8JP.framer-6j1x0h, .framer-Xi8JP .framer-6j1x0h { display: block; }",
  ".framer-Xi8JP.framer-uka4gs { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 46px; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 47px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-Xi8JP .framer-t4ypgj { -webkit-user-select: none; aspect-ratio: 1.1818181818181819 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; user-select: none; width: 26px; }",
  ".framer-Xi8JP.framer-v-hd81jr.framer-uka4gs, .framer-Xi8JP.framer-v-19g2rw1.framer-uka4gs, .framer-Xi8JP.framer-v-uka4gs.hover.framer-uka4gs { aspect-ratio: 1.0217391304347827 / 1; height: var(--framer-aspect-ratio-supported, 46px); }",
  ".framer-Xi8JP.framer-v-hd81jr .framer-t4ypgj { aspect-ratio: 1.0526315789473684 / 1; height: var(--framer-aspect-ratio-supported, 23px); width: 24px; }",
  ".framer-Xi8JP.framer-v-19g2rw1 .framer-t4ypgj { aspect-ratio: 1.2941176470588236 / 1; height: var(--framer-aspect-ratio-supported, 27px); width: 35px; }",
  '.framer-Xi8JP[data-border="true"]::after, .framer-Xi8JP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 46
 * @framerIntrinsicWidth 47
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"OL0h8sJcY":{"layout":["fixed","fixed"]},"jNT1niBTh":{"layout":["fixed","fixed"]},"Orn_1awcs":{"layout":["fixed","fixed"]},"gVPEmUKjN":{"layout":["fixed","fixed"]},"H18YyDkcS":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"gR9_gy1KR":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerZrbdnhbfF = withCSS(Component, css, "framer-Xi8JP");
export default FramerZrbdnhbfF;
FramerZrbdnhbfF.displayName = "Social Link";
FramerZrbdnhbfF.defaultProps = { height: 46, width: 47 };
addPropertyControls(FramerZrbdnhbfF, {
  variant: {
    options: ["x1uW2jaoq", "OL0h8sJcY", "jNT1niBTh"],
    optionTitles: ["Telegram", "X", "Discord"],
    title: "Variant",
    type: ControlType.Enum,
  },
  gR9_gy1KR: { title: "Link", type: ControlType.Link },
});
addFonts(FramerZrbdnhbfF, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerZrbdnhbfF",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"OL0h8sJcY":{"layout":["fixed","fixed"]},"jNT1niBTh":{"layout":["fixed","fixed"]},"Orn_1awcs":{"layout":["fixed","fixed"]},"gVPEmUKjN":{"layout":["fixed","fixed"]},"H18YyDkcS":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicHeight: "46",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerVariables: '{"gR9_gy1KR":"link"}',
        framerIntrinsicWidth: "47",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ZrbdnhbfF.map
