// Generated by Framer (9d598a4)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/5bdfLqH6lT8T5xf4GMV4/1JdpUmOMiu0WMRRWpxBJ/m8DU6sDyG.js";
const enabledGestures = { y_lLBTIbB: { hover: true } };
const serializationHash = "framer-ujHFz";
const variantClassNames = { y_lLBTIbB: "framer-v-1t0mfki" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, link, text, width, ...props }) => {
  return {
    ...props,
    QDl07_yb4: text ?? props.QDl07_yb4 ?? "Privacy Policy",
    XakXd1OLN: link ?? props.XakXd1OLN,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    QDl07_yb4,
    XakXd1OLN,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "y_lLBTIbB",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: XakXd1OLN,
          motionChild: true,
          nodeId: "y_lLBTIbB",
          scopeId: "t9ArLtR57",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1t0mfki",
              className,
              classNames
            )} framer-1sfsyx5`,
            "data-framer-name": "Default",
            layoutDependency: layoutDependency,
            layoutId: "y_lLBTIbB",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { "y_lLBTIbB-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-1gou2ux",
                  "data-styles-preset": "m8DU6sDyG",
                  style: {
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                  },
                  children: "Privacy Policy",
                }),
              }),
              className: "framer-1cdv6my",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "dqMAO1RhV",
              style: {
                "--extracted-r6o4lv":
                  "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
                "--framer-paragraph-spacing": "0px",
              },
              text: QDl07_yb4,
              variants: {
                "y_lLBTIbB-hover": {
                  "--extracted-r6o4lv":
                    "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
                },
              },
              verticalAlignment: "top",
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  "y_lLBTIbB-hover": {
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-1gou2ux",
                        "data-styles-preset": "m8DU6sDyG",
                        style: {
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61)))",
                        },
                        children: "Privacy Policy",
                      }),
                    }),
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ujHFz.framer-1sfsyx5, .framer-ujHFz .framer-1sfsyx5 { display: block; }",
  ".framer-ujHFz.framer-1t0mfki { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-ujHFz .framer-1cdv6my { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ujHFz.framer-1t0mfki { gap: 0px; } .framer-ujHFz.framer-1t0mfki > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-ujHFz.framer-1t0mfki > :first-child { margin-left: 0px; } .framer-ujHFz.framer-1t0mfki > :last-child { margin-right: 0px; } }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 21.5
 * @framerIntrinsicWidth 127.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"JxbM5jkgK":{"layout":["auto","auto"]}}}
 * @framerVariables {"QDl07_yb4":"text","XakXd1OLN":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const Framert9ArLtR57 = withCSS(Component, css, "framer-ujHFz");
export default Framert9ArLtR57;
Framert9ArLtR57.displayName = "Link";
Framert9ArLtR57.defaultProps = { height: 21.5, width: 127.5 };
addPropertyControls(Framert9ArLtR57, {
  QDl07_yb4: {
    defaultValue: "Privacy Policy",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  XakXd1OLN: { title: "Link", type: ControlType.Link },
});
addFonts(
  Framert9ArLtR57,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framert9ArLtR57",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerVariables: '{"QDl07_yb4":"text","XakXd1OLN":"link"}',
        framerIntrinsicWidth: "127.5",
        framerIntrinsicHeight: "21.5",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"JxbM5jkgK":{"layout":["auto","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
