// Generated by Framer (9f1494d)
import { fontStore } from "framer";
fontStore.loadFonts(["FS;Laila-semibold", "FS;Laila-bold"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Laila",
        source: "fontshare",
        style: "normal",
        url: "../framerusercontent.com/third-party-assets/fontshare/wf/4YKBLVWJIJ647PIYGZD676MF72B7VQP2/XUMTNUY3P7RNZPK72ECWVPZBRLPZVT7C/GQNGN6DN2ZMTM7LRYRBYZ3F2M55SISX6.woff2",
        weight: "600",
      },
      {
        family: "Laila",
        source: "fontshare",
        style: "normal",
        url: "../framerusercontent.com/third-party-assets/fontshare/wf/T7CBH3JGFATYBL5TNV645OUSMJKFAS4V/23Z3IE7VQJGXQQ2SBCEVM4B52EFEYA65/XDTEY6U6MH3EO3V3YVYTSQGDIBCZMBX4.woff2",
        weight: "700",
      },
    ],
  },
];
export const css = [
  ".framer-qyXbd .framer-styles-preset-1eat30k:not(.rich-text-wrapper), .framer-qyXbd .framer-styles-preset-1eat30k.rich-text-wrapper p { --framer-font-family: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-family-bold: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }",
  "@media (max-width: 1199px) and (min-width: 810px) { .framer-qyXbd .framer-styles-preset-1eat30k:not(.rich-text-wrapper), .framer-qyXbd .framer-styles-preset-1eat30k.rich-text-wrapper p { --framer-font-family: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-family-bold: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }",
  "@media (max-width: 809px) and (min-width: 0px) { .framer-qyXbd .framer-styles-preset-1eat30k:not(.rich-text-wrapper), .framer-qyXbd .framer-styles-preset-1eat30k.rich-text-wrapper p { --framer-font-family: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-family-bold: \"Laila\", \"Laila Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }",
];
export const className = "framer-qyXbd";
export const __FramerMetadata__ = {
  exports: {
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
