// Generated by Framer (9d598a4)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Clipboard from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js";
const ClipboardFonts = getFonts(Clipboard);
const cycleOrder = ["YMtl12FbF", "bdI2pJmrr"];
const serializationHash = "framer-XmFm0";
const variantClassNames = {
  bdI2pJmrr: "framer-v-1cinzq6",
  YMtl12FbF: "framer-v-1f57to3",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Copied: "bdI2pJmrr", Default: "YMtl12FbF" };
const getProps = ({ content, height, id, width, ...props }) => {
  return {
    ...props,
    DTUIEisSq: content ?? props.DTUIEisSq,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "YMtl12FbF",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, DTUIEisSq, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "YMtl12FbF",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapqfsabd = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("bdI2pJmrr");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1f57to3",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "YMtl12FbF",
          onTap: onTapqfsabd,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              bdI2pJmrr: {
                "data-framer-name": "Copied",
                "data-highlight": undefined,
                onTap: undefined,
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-4pq4t4",
              "data-framer-name": "Content",
              layoutDependency: layoutDependency,
              layoutId: "pDGh_b1wj",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h5, {
                      style: {
                        "--font-selector": "R0Y7THVja2llc3QgR3V5LXJlZ3VsYXI=",
                        "--framer-font-family": '"Luckiest Guy", sans-serif',
                        "--framer-font-size": "18px",
                        "--framer-letter-spacing": "0px",
                        "--framer-line-height": "1.1em",
                        "--framer-text-alignment": "left",
                        "--framer-text-color":
                          "var(--extracted-1lwpl3i, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                      },
                      children: "Copy",
                    }),
                  }),
                  className: "framer-8xwn00",
                  fonts: ["GF;Luckiest Guy-regular"],
                  layoutDependency: layoutDependency,
                  layoutId: "oAXTRjMqL",
                  style: {
                    "--extracted-1lwpl3i":
                      "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    "--framer-paragraph-spacing": "0px",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      bdI2pJmrr: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h5, {
                            style: {
                              "--font-selector":
                                "R0Y7THVja2llc3QgR3V5LXJlZ3VsYXI=",
                              "--framer-font-family":
                                '"Luckiest Guy", sans-serif',
                              "--framer-font-size": "18px",
                              "--framer-letter-spacing": "0px",
                              "--framer-line-height": "1.1em",
                              "--framer-text-alignment": "left",
                              "--framer-text-color":
                                "var(--extracted-1lwpl3i, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                            },
                            children: "Copied",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1hrk47u",
                  "data-framer-name": "Icon",
                  layoutDependency: layoutDependency,
                  layoutId: "aXCuvRpAO",
                  style: {
                    backgroundColor:
                      "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    mask: "url('https://framerusercontent.com/images/ntlS9V0k5C5M7xaZTL2O5Jf5E9I.svg') alpha no-repeat center / cover add",
                    WebkitMask:
                      "url('https://framerusercontent.com/images/ntlS9V0k5C5M7xaZTL2O5Jf5E9I.svg') alpha no-repeat center / cover add",
                  },
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-mpvwbr-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "X99EB72PL-container",
                nodeId: "X99EB72PL",
                rendersWithMotion: true,
                scopeId: "P4JARSZGA",
                children: /*#__PURE__*/ _jsx(Clipboard, {
                  borderRadius: 50,
                  bottomLeftRadius: 50,
                  bottomRightRadius: 50,
                  color:
                    "var(--token-33a1c34f-c2a3-4afa-ad64-bdcf0c235d64, rgba(255, 255, 255, 0))",
                  content: DTUIEisSq,
                  fill: "var(--token-33a1c34f-c2a3-4afa-ad64-bdcf0c235d64, rgba(255, 255, 255, 0))",
                  font: {},
                  height: "100%",
                  id: "X99EB72PL",
                  isMixedBorderRadius: false,
                  label: "",
                  layoutId: "X99EB72PL",
                  padding: 10,
                  paddingBottom: 10,
                  paddingLeft: 10,
                  paddingPerSide: false,
                  paddingRight: 10,
                  paddingTop: 10,
                  style: { height: "100%", width: "100%" },
                  topLeftRadius: 50,
                  topRightRadius: 50,
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-XmFm0.framer-mu420i, .framer-XmFm0 .framer-mu420i { display: block; }",
  ".framer-XmFm0.framer-1f57to3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-XmFm0 .framer-4pq4t4 { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; user-select: none; width: min-content; }",
  ".framer-XmFm0 .framer-8xwn00 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-XmFm0 .framer-1hrk47u { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); overflow: hidden; position: relative; width: 23px; }",
  ".framer-XmFm0 .framer-mpvwbr-container { -webkit-user-select: none; flex: none; height: 100%; position: absolute; right: 0px; top: calc(48.14814814814817% - 100% / 2); user-select: none; width: 100%; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-XmFm0.framer-1f57to3, .framer-XmFm0 .framer-4pq4t4 { gap: 0px; } .framer-XmFm0.framer-1f57to3 > *, .framer-XmFm0 .framer-4pq4t4 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-XmFm0.framer-1f57to3 > :first-child, .framer-XmFm0 .framer-4pq4t4 > :first-child { margin-left: 0px; } .framer-XmFm0.framer-1f57to3 > :last-child, .framer-XmFm0 .framer-4pq4t4 > :last-child { margin-right: 0px; } }",
  ".framer-XmFm0.framer-v-1cinzq6.framer-1f57to3 { cursor: unset; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 23
 * @framerIntrinsicWidth 73
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"bdI2pJmrr":{"layout":["auto","auto"]}}}
 * @framerVariables {"DTUIEisSq":"content"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerP4JARSZGA = withCSS(Component, css, "framer-XmFm0");
export default FramerP4JARSZGA;
FramerP4JARSZGA.displayName = "Copy Button";
FramerP4JARSZGA.defaultProps = { height: 23, width: 73 };
addPropertyControls(FramerP4JARSZGA, {
  variant: {
    options: ["YMtl12FbF", "bdI2pJmrr"],
    optionTitles: ["Default", "Copied"],
    title: "Variant",
    type: ControlType.Enum,
  },
  DTUIEisSq: {
    defaultValue: "",
    displayTextArea: true,
    title: "Content",
    type: ControlType.String,
  },
});
addFonts(
  FramerP4JARSZGA,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Luckiest Guy",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/luckiestguy/v23/_gP_1RrxsjcxVyin9l9n_j2RT9R3qDpraA.woff2",
          weight: "400",
        },
      ],
    },
    ...ClipboardFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerP4JARSZGA",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"bdI2pJmrr":{"layout":["auto","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerVariables: '{"DTUIEisSq":"content"}',
        framerIntrinsicHeight: "23",
        framerIntrinsicWidth: "73",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./P4JARSZGA.map
