// Generated by Framer (beb597f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Image,
  Link,
  ResolveLinks,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle2 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/hTZKnjrJdEx7iJZEvI4a/QPNxOS8UItmriqASyisT/m8DU6sDyG.js";
import * as sharedStyle3 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/wPAery0uUEG9QKIVG4KE/BVDKLLDt8UHp86znd4An/maGGuEvsJ.js";
import * as sharedStyle from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/gTrtBp7gJ5zKPcJq9oW8/99oCjLxlqF55URVnLngr/P6QrEhIx_.js";
import * as sharedStyle1 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/A4Rhs3kfCcK6G7a277fz/6G8xZ9mzCiymva6SzShu/VgWUtp2Rd.js";
import Logo from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/mwtuTDjLRWmCnXFSPqXH/QLXg5cs3CZFaZkZhiVog/bWCjYCsf5.js";
import Button from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/6iQnPT6QWpALdNioZ1Vc/vuWMO7Mf7xEXVds3Cnze/Dc_z1yLfb.js";
import Link1 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/swkVOEliAG7SvBUf1xnC/e5BckhRimVlYmFBMoHLa/t9ArLtR57.js";
import SocialLink from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/gj09UedkVkDb0Xzt0TXm/uwAlzFGMuW8AlMdscPL9/ZrbdnhbfF.js";
const ImageWithFX = withFX(Image);
const MotionDivWithFX = withFX(motion.div);
const ButtonFonts = getFonts(Button);
const SmartComponentScopedContainerWithFX = withFX(
  SmartComponentScopedContainer
);
const SocialLinkFonts = getFonts(SocialLink);
const LogoFonts = getFonts(Logo);
const Link1Fonts = getFonts(Link1);
const cycleOrder = ["xJvyj9BDJ", "ajxLpnJUX", "VJeGkoAO8"];
const serializationHash = "framer-mfTJr";
const variantClassNames = {
  ajxLpnJUX: "framer-v-1oitkep",
  VJeGkoAO8: "framer-v-hav8xk",
  xJvyj9BDJ: "framer-v-9ih1cv",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const QirT5gtEY = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.8,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 50,
};
const transition2 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 50,
};
const transition3 = {
  damping: 60,
  delay: 0.1,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const transition4 = {
  damping: 60,
  delay: 0.2,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const transition5 = {
  damping: 60,
  delay: 0.3,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 30,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Desktop: "xJvyj9BDJ",
  Phone: "VJeGkoAO8",
  Tablet: "ajxLpnJUX",
};
const getProps = ({ height, id, logoLink, width, ...props }) => {
  return {
    ...props,
    QirT5gtEY: logoLink ?? props.QirT5gtEY,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "xJvyj9BDJ",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, QirT5gtEY, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "xJvyj9BDJ",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  const isDisplayed = () => {
    if (baseVariant === "VJeGkoAO8") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.footer, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-9ih1cv",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "xJvyj9BDJ",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              ajxLpnJUX: { "data-framer-name": "Tablet" },
              VJeGkoAO8: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-wp98lf",
            "data-framer-name": "Container",
            layoutDependency: layoutDependency,
            layoutId: "n3wmWjYQk",
            children: [
              /*#__PURE__*/ _jsx(ImageWithFX, {
                __framer__animate: { transition: transition2 },
                __framer__animateOnce: true,
                __framer__enter: animation,
                __framer__styleAppearEffectEnabled: true,
                __framer__threshold: 0.5,
                __perspectiveFX: false,
                __smartComponentFX: true,
                __targetOpacity: 1,
                background: {
                  alt: "Character",
                  fit: "fill",
                  pixelHeight: 1024,
                  pixelWidth: 1024,
                  sizes: `calc(min(${
                    componentViewport?.width || "100vw"
                  } - 60px, 1170px) * 0.1553)`,
                  src: "https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?width=1024&height=1024",
                  srcSet:
                    "https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?width=1024&height=1024 1024w",
                },
                className: "framer-2s24gv",
                "data-framer-name": "Character Top",
                layoutDependency: layoutDependency,
                layoutId: "VsKpO_Bum",
                transformTemplate: transformTemplate1,
                ...addPropertyOverrides(
                  {
                    VJeGkoAO8: {
                      background: {
                        alt: "Character",
                        fit: "fill",
                        pixelHeight: 1024,
                        pixelWidth: 1024,
                        sizes: `calc(min(${
                          componentViewport?.width || "100vw"
                        } - 40px, 1170px) / 3.211)`,
                        src: "https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?width=1024&height=1024",
                        srcSet:
                          "https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/MnY694EIki7ip3TOCOCH2unOBtQ.png?width=1024&height=1024 1024w",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-rtlp78",
                "data-border": true,
                "data-framer-name": "CTA",
                layoutDependency: layoutDependency,
                layoutId: "upX07KSCI",
                style: {
                  "--border-bottom-width": "7px",
                  "--border-color":
                    "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                  "--border-left-width": "7px",
                  "--border-right-width": "7px",
                  "--border-style": "solid",
                  "--border-top-width": "7px",
                  backgroundColor:
                    "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
                  borderBottomLeftRadius: 49,
                  borderBottomRightRadius: 49,
                  borderTopLeftRadius: 49,
                  borderTopRightRadius: 49,
                },
                variants: {
                  ajxLpnJUX: {
                    "--border-bottom-width": "4px",
                    "--border-left-width": "4px",
                    "--border-right-width": "4px",
                    "--border-top-width": "4px",
                  },
                  VJeGkoAO8: {
                    "--border-bottom-width": "4px",
                    "--border-left-width": "4px",
                    "--border-right-width": "4px",
                    "--border-top-width": "4px",
                    borderBottomLeftRadius: 30,
                    borderBottomRightRadius: 30,
                    borderTopLeftRadius: 30,
                    borderTopRightRadius: 30,
                  },
                },
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-t8qkff",
                  "data-border": true,
                  "data-framer-name": "BG",
                  layoutDependency: layoutDependency,
                  layoutId: "KMbBekE0v",
                  style: {
                    "--border-bottom-width": "4px",
                    "--border-color":
                      "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    "--border-left-width": "4px",
                    "--border-right-width": "4px",
                    "--border-style": "solid",
                    "--border-top-width": "4px",
                    background:
                      "radial-gradient(53% 140% at 32.5% -19.400000000000002%, var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204)) 0%, var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255)) 50%)",
                    borderBottomLeftRadius: 50,
                    borderBottomRightRadius: 50,
                    borderTopLeftRadius: 50,
                    borderTopRightRadius: 50,
                    boxShadow:
                      "0px 4px 0px 0px var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                  },
                  variants: {
                    ajxLpnJUX: {
                      "--border-bottom-width": "2px",
                      "--border-left-width": "2px",
                      "--border-right-width": "2px",
                      "--border-top-width": "2px",
                      boxShadow:
                        "0px 2px 0px 0px var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    },
                    VJeGkoAO8: {
                      "--border-bottom-width": "2px",
                      "--border-left-width": "2px",
                      "--border-right-width": "2px",
                      "--border-top-width": "2px",
                      borderBottomLeftRadius: 30,
                      borderBottomRightRadius: 30,
                      borderTopLeftRadius: 30,
                      borderTopRightRadius: 30,
                      boxShadow:
                        "0px 2px 0px 0px var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    },
                  },
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      "aria-label": "Shape",
                      className: "framer-p8nw3y",
                      "data-framer-name": "Shape 01",
                      layoutDependency: layoutDependency,
                      layoutId: "zXk9bmEaS",
                      style: {
                        backgroundColor:
                          "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204))",
                        mask: "url('https://framerusercontent.com/images/jkv3EJQjha026g4Uu7vl3Uoadk.svg?width=52&height=19') alpha no-repeat center / cover add",
                        WebkitMask:
                          "url('https://framerusercontent.com/images/jkv3EJQjha026g4Uu7vl3Uoadk.svg?width=52&height=19') alpha no-repeat center / cover add",
                      },
                      transformTemplate: transformTemplate1,
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      "aria-label": "Shape",
                      className: "framer-1fxb95w",
                      "data-framer-name": "Shape 02",
                      layoutDependency: layoutDependency,
                      layoutId: "b1rvace6Y",
                      style: {
                        backgroundColor:
                          "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204))",
                        mask: "url('https://framerusercontent.com/images/jkv3EJQjha026g4Uu7vl3Uoadk.svg?width=52&height=19') alpha no-repeat center / cover add",
                        WebkitMask:
                          "url('https://framerusercontent.com/images/jkv3EJQjha026g4Uu7vl3Uoadk.svg?width=52&height=19') alpha no-repeat center / cover add",
                      },
                      transformTemplate: transformTemplate1,
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      "aria-label": "Shape",
                      className: "framer-kf7dxg",
                      "data-framer-name": "Shape 03",
                      layoutDependency: layoutDependency,
                      layoutId: "j6wHScfVS",
                      style: {
                        backgroundColor:
                          "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204))",
                        mask: "url('https://framerusercontent.com/images/5Y2IQkJZG70sgAva3SZcOfvgKM.svg?width=155&height=44') alpha no-repeat center / cover add",
                        WebkitMask:
                          "url('https://framerusercontent.com/images/5Y2IQkJZG70sgAva3SZcOfvgKM.svg?width=155&height=44') alpha no-repeat center / cover add",
                      },
                      transformTemplate: transformTemplate1,
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-4p13sd",
                      "data-framer-name": "Content",
                      layoutDependency: layoutDependency,
                      layoutId: "F8RR06h1r",
                      children: [
                        /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                          __framer__animate: { transition: transition2 },
                          __framer__animateOnce: true,
                          __framer__enter: animation1,
                          __framer__styleAppearEffectEnabled: true,
                          __framer__threshold: 0.5,
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          className: "framer-3wqid8",
                          "data-framer-name": "Title",
                          layoutDependency: layoutDependency,
                          layoutId: "OTIB7lrlo",
                          children: [
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h2, {
                                  className: "framer-styles-preset-uy3tjv",
                                  "data-styles-preset": "P6QrEhIx_",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-1of0zx5, rgb(0, 0, 0))",
                                  },
                                  children: "Community",
                                }),
                              }),
                              className: "framer-1bnzlos",
                              fonts: ["Inter"],
                              layoutDependency: layoutDependency,
                              layoutId: "jHpiVTtHZ",
                              style: {
                                "--extracted-1of0zx5": "rgb(0, 0, 0)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--framer-paragraph-spacing": "0px",
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                            /*#__PURE__*/ _jsx(RichText, {
                              __fromCanvasComponent: true,
                              children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                  className: "framer-styles-preset-n1xc3h",
                                  "data-styles-preset": "VgWUtp2Rd",
                                  style: {
                                    "--framer-text-alignment": "center",
                                    "--framer-text-color":
                                      "var(--extracted-r6o4lv, rgb(0, 0, 0))",
                                  },
                                  children:
                                    "Join us as we grow, build, and take NOOB beyond the moon.",
                                }),
                              }),
                              className: "framer-1adt9ib",
                              fonts: ["Inter"],
                              layoutDependency: layoutDependency,
                              layoutId: "XQsLzeMtY",
                              style: {
                                "--extracted-r6o4lv": "rgb(0, 0, 0)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--framer-paragraph-spacing": "0px",
                              },
                              verticalAlignment: "top",
                              withExternalLayout: true,
                            }),
                          ],
                        }),
                        /*#__PURE__*/ _jsxs(motion.div, {
                          className: "framer-1t7y4n4",
                          "data-framer-name": "Button + Socials",
                          layoutDependency: layoutDependency,
                          layoutId: "dTqzxZuo9",
                          children: [
                            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                              height: 52,
                              children: /*#__PURE__*/ _jsx(
                                SmartComponentScopedContainerWithFX,
                                {
                                  __framer__animate: {
                                    transition: transition2,
                                  },
                                  __framer__animateOnce: true,
                                  __framer__enter: animation1,
                                  __framer__styleAppearEffectEnabled: true,
                                  __framer__threshold: 0.5,
                                  __perspectiveFX: false,
                                  __smartComponentFX: true,
                                  __targetOpacity: 1,
                                  className: "framer-13jbem0-container",
                                  layoutDependency: layoutDependency,
                                  layoutId: "L0py6mYZr-container",
                                  nodeId: "L0py6mYZr",
                                  rendersWithMotion: true,
                                  scopeId: "CbPIrLAGo",
                                  children: /*#__PURE__*/ _jsx(Button, {
                                    height: "100%",
                                    id: "L0py6mYZr",
                                    layoutId: "L0py6mYZr",
                                    MKPg9WbcL: "Buy Now",
                                    QUXmHzKkq: false,
                                    variant: "u9cHE4zsd",
                                    width: "100%",
                                  }),
                                }
                              ),
                            }),
                            /*#__PURE__*/ _jsxs(motion.div, {
                              className: "framer-ifmgpy",
                              "data-framer-name": "Socials",
                              layoutDependency: layoutDependency,
                              layoutId: "aKLLjQuT2",
                              children: [
                                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                  height: 46,
                                  children: /*#__PURE__*/ _jsx(
                                    SmartComponentScopedContainerWithFX,
                                    {
                                      __framer__animate: {
                                        transition: transition3,
                                      },
                                      __framer__animateOnce: true,
                                      __framer__enter: animation1,
                                      __framer__styleAppearEffectEnabled: true,
                                      __framer__threshold: 0.5,
                                      __perspectiveFX: false,
                                      __smartComponentFX: true,
                                      __targetOpacity: 1,
                                      className: "framer-1ecko0-container",
                                      layoutDependency: layoutDependency,
                                      layoutId: "cXRtqffuS-container",
                                      nodeId: "cXRtqffuS",
                                      rendersWithMotion: true,
                                      scopeId: "CbPIrLAGo",
                                      ...addPropertyOverrides(
                                        {
                                          VJeGkoAO8: {
                                            __framer__animate: {
                                              transition: transition2,
                                            },
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                      children: /*#__PURE__*/ _jsx(SocialLink, {
                                        gR9_gy1KR: "https://t.me/NOOBonETH",
                                        height: "100%",
                                        id: "cXRtqffuS",
                                        layoutId: "cXRtqffuS",
                                        variant: "x1uW2jaoq",
                                        width: "100%",
                                      }),
                                    }
                                  ),
                                }),
                                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                  height: 46,
                                  children: /*#__PURE__*/ _jsx(
                                    SmartComponentScopedContainerWithFX,
                                    {
                                      __framer__animate: {
                                        transition: transition4,
                                      },
                                      __framer__animateOnce: true,
                                      __framer__enter: animation1,
                                      __framer__styleAppearEffectEnabled: true,
                                      __framer__threshold: 0.5,
                                      __perspectiveFX: false,
                                      __smartComponentFX: true,
                                      __targetOpacity: 1,
                                      className: "framer-1cmcmhf-container",
                                      layoutDependency: layoutDependency,
                                      layoutId: "lO6ZWnw17-container",
                                      nodeId: "lO6ZWnw17",
                                      rendersWithMotion: true,
                                      scopeId: "CbPIrLAGo",
                                      style: { rotate: -5 },
                                      ...addPropertyOverrides(
                                        {
                                          VJeGkoAO8: {
                                            __framer__animate: {
                                              transition: transition3,
                                            },
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                      children: /*#__PURE__*/ _jsx(SocialLink, {
                                        gR9_gy1KR:
                                          "https://x.com/NoobStillHere",
                                        height: "100%",
                                        id: "lO6ZWnw17",
                                        layoutId: "lO6ZWnw17",
                                        variant: "OL0h8sJcY",
                                        width: "100%",
                                      }),
                                    }
                                  ),
                                }),
                                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                  height: 46,
                                  children: /*#__PURE__*/ _jsx(
                                    SmartComponentScopedContainerWithFX,
                                    {
                                      __framer__animate: {
                                        transition: transition5,
                                      },
                                      __framer__animateOnce: true,
                                      __framer__enter: animation1,
                                      __framer__styleAppearEffectEnabled: true,
                                      __framer__threshold: 0.5,
                                      __perspectiveFX: false,
                                      __smartComponentFX: true,
                                      __targetOpacity: 1,
                                      className: "framer-1dvpbt9-container",
                                      layoutDependency: layoutDependency,
                                      layoutId: "HpAGj94eQ-container",
                                      nodeId: "HpAGj94eQ",
                                      rendersWithMotion: true,
                                      scopeId: "CbPIrLAGo",
                                      ...addPropertyOverrides(
                                        {
                                          VJeGkoAO8: {
                                            __framer__animate: {
                                              transition: transition4,
                                            },
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                      children: /*#__PURE__*/ _jsx(SocialLink, {
                                        gR9_gy1KR:
                                          "https://dexscreener.com/ethereum/0x0xComingSoon",
                                        height: "100%",
                                        id: "HpAGj94eQ",
                                        layoutId: "HpAGj94eQ",
                                        variant: "jNT1niBTh",
                                        width: "100%",
                                      }),
                                    }
                                  ),
                                }),
                              ],
                            }),
                          ],
                        }),
                      ],
                    }),
                  ],
                }),
              }),
              /*#__PURE__*/ _jsx(ImageWithFX, {
                __framer__animate: { transition: transition5 },
                __framer__animateOnce: true,
                __framer__enter: animation,
                __framer__styleAppearEffectEnabled: true,
                __framer__threshold: 0.5,
                __perspectiveFX: false,
                __smartComponentFX: true,
                __targetOpacity: 1,
                background: {
                  alt: "Character",
                  fit: "fill",
                  pixelHeight: 1024,
                  pixelWidth: 1536,
                  sizes: `calc(min(${
                    componentViewport?.width || "100vw"
                  } - 60px, 1170px) * 0.3196)`,
                  src: "https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?width=1536&height=1024",
                  srcSet:
                    "https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?scale-down-to=512&width=1536&height=1024 512w,https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?scale-down-to=1024&width=1536&height=1024 1024w,https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?width=1536&height=1024 1536w",
                },
                className: "framer-1w1nrx5",
                "data-framer-name": "Character",
                layoutDependency: layoutDependency,
                layoutId: "aMx1Qk_ME",
                transformTemplate: transformTemplate1,
                ...addPropertyOverrides(
                  {
                    VJeGkoAO8: {
                      __framer__animate: { transition: transition4 },
                      background: {
                        alt: "Character",
                        fit: "fill",
                        pixelHeight: 1024,
                        pixelWidth: 1536,
                        sizes: `calc(min(${
                          componentViewport?.width || "100vw"
                        } - 40px, 1170px) / 2.071)`,
                        src: "https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?width=1536&height=1024",
                        srcSet:
                          "https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?scale-down-to=512&width=1536&height=1024 512w,https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?scale-down-to=1024&width=1536&height=1024 1024w,https://framerusercontent.com/images/PugWPimK4RZm9191EBF3dX02LqE.png?width=1536&height=1024 1536w",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                className: "framer-dkonb2",
                "data-border": true,
                "data-framer-name": "Copyright",
                layoutDependency: layoutDependency,
                layoutId: "JbqExte0H",
                style: {
                  "--border-bottom-width": "2px",
                  "--border-color":
                    "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                  "--border-left-width": "2px",
                  "--border-right-width": "2px",
                  "--border-style": "solid",
                  "--border-top-width": "2px",
                  backgroundColor:
                    "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                  borderBottomLeftRadius: 16,
                  borderBottomRightRadius: 16,
                  borderTopLeftRadius: 16,
                  borderTopRightRadius: 16,
                  boxShadow:
                    "0px 4px 0px 0px var(--token-ebf707e2-9a0d-49da-bcbe-2b81e97334fa, rgb(0, 0, 0))",
                },
                variants: {
                  ajxLpnJUX: {
                    boxShadow:
                      "0px 2px 0px 0px var(--token-ebf707e2-9a0d-49da-bcbe-2b81e97334fa, rgb(0, 0, 0))",
                  },
                  VJeGkoAO8: {
                    boxShadow:
                      "0px 2px 0px 0px var(--token-ebf707e2-9a0d-49da-bcbe-2b81e97334fa, rgb(0, 0, 0))",
                  },
                },
                ...addPropertyOverrides(
                  {
                    VJeGkoAO8: {
                      __framer__animate: { transition: transition2 },
                      __framer__animateOnce: true,
                      __framer__enter: animation2,
                      __framer__styleAppearEffectEnabled: true,
                      __framer__threshold: 0,
                      __perspectiveFX: false,
                      __smartComponentFX: true,
                      __targetOpacity: 1,
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-1gou2ux",
                        "data-styles-preset": "m8DU6sDyG",
                        children: /*#__PURE__*/ _jsx(Link, {
                          href: "T.ME/EVERGREENDEV",
                          motionChild: true,
                          nodeId: "WwisZRJGD",
                          openInNewTab: true,
                          relValues: [],
                          scopeId: "CbPIrLAGo",
                          smoothScroll: false,
                          children: /*#__PURE__*/ _jsx(motion.a, {
                            className: "framer-styles-preset-s58osx",
                            "data-styles-preset": "maGGuEvsJ",
                            children: "2025 \xa9 NOOB - Built by EGSTUDIOS",
                          }),
                        }),
                      }),
                    }),
                    className: "framer-nngp5w",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "WwisZRJGD",
                    style: { "--framer-paragraph-spacing": "0px" },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        ajxLpnJUX: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1gou2ux",
                              "data-styles-preset": "m8DU6sDyG",
                              style: { "--framer-text-alignment": "center" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: "T.ME/EVERGREENDEV",
                                motionChild: true,
                                nodeId: "WwisZRJGD",
                                openInNewTab: true,
                                relValues: [],
                                scopeId: "CbPIrLAGo",
                                smoothScroll: false,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-s58osx",
                                  "data-styles-preset": "maGGuEvsJ",
                                  children:
                                    "2025 \xa9 NOOB - Built by EGSTUDIOS",
                                }),
                              }),
                            }),
                          }),
                        },
                        VJeGkoAO8: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1gou2ux",
                              "data-styles-preset": "m8DU6sDyG",
                              style: { "--framer-text-alignment": "center" },
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: "T.ME/EVERGREENDEV",
                                motionChild: true,
                                nodeId: "WwisZRJGD",
                                openInNewTab: true,
                                relValues: [],
                                scopeId: "CbPIrLAGo",
                                smoothScroll: false,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-s58osx",
                                  "data-styles-preset": "maGGuEvsJ",
                                  children:
                                    "2025 \xa9 NOOB - Built by EGSTUDIOS",
                                }),
                              }),
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 74,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainerWithFX,
                      {
                        __framer__animate: { transition: transition3 },
                        __framer__animateOnce: true,
                        __framer__enter: animation2,
                        __framer__styleAppearEffectEnabled: true,
                        __framer__threshold: 0,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        className: "framer-145e5ss-container",
                        layoutDependency: layoutDependency,
                        layoutId: "fCZh864cT-container",
                        nodeId: "fCZh864cT",
                        rendersWithMotion: true,
                        scopeId: "CbPIrLAGo",
                        ...addPropertyOverrides(
                          {
                            VJeGkoAO8: {
                              __framer__styleAppearEffectEnabled: undefined,
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                        children: /*#__PURE__*/ _jsx(Logo, {
                          height: "100%",
                          id: "fCZh864cT",
                          iIiG4RFTv: QirT5gtEY,
                          layoutId: "fCZh864cT",
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                    __framer__animate: { transition: transition2 },
                    __framer__animateOnce: true,
                    __framer__enter: animation2,
                    __framer__styleAppearEffectEnabled: true,
                    __framer__threshold: 0,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: "framer-1kjbwxc",
                    "data-framer-name": "Links",
                    layoutDependency: layoutDependency,
                    layoutId: "muq5HilIG",
                    ...addPropertyOverrides(
                      {
                        VJeGkoAO8: {
                          __framer__styleAppearEffectEnabled: undefined,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: [
                      /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "privacy-policy" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "LScAxijjv",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "privacy-policy" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "LScAxijjv",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "privacy-policy" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "LScAxijjv",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                        ],
                        children: (resolvedLinks) =>
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 21,
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-6i0aye-container",
                                layoutDependency: layoutDependency,
                                layoutId: "iTCk8kF0n-container",
                                nodeId: "iTCk8kF0n",
                                rendersWithMotion: true,
                                scopeId: "CbPIrLAGo",
                                children: /*#__PURE__*/ _jsx(Link1, {
                                  height: "100%",
                                  id: "iTCk8kF0n",
                                  layoutId: "iTCk8kF0n",
                                  QDl07_yb4: "Privacy Policy",
                                  width: "100%",
                                  XakXd1OLN: resolvedLinks[0],
                                  ...addPropertyOverrides(
                                    {
                                      ajxLpnJUX: {
                                        XakXd1OLN: resolvedLinks[1],
                                      },
                                      VJeGkoAO8: {
                                        XakXd1OLN: resolvedLinks[2],
                                      },
                                    },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                      }),
                      isDisplayed() &&
                        /*#__PURE__*/ _jsx(motion.div, {
                          "aria-label": "Divider",
                          className: "framer-hwjnl",
                          "data-framer-name": "Divider",
                          layoutDependency: layoutDependency,
                          layoutId: "yXdaEonrZ",
                          style: {
                            backgroundColor:
                              "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                          },
                        }),
                      /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "terms-conditions" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "ptA7HbB9O",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "terms-conditions" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "ptA7HbB9O",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                          {
                            href: {
                              pathVariables: { XFTVW7bQ0: "terms-conditions" },
                              unresolvedPathSlugs: {
                                XFTVW7bQ0: {
                                  collectionId: "mI3iVRuBC",
                                  collectionItemId: "ptA7HbB9O",
                                },
                              },
                              webPageId: "sVSTYim4n",
                            },
                            implicitPathVariables: undefined,
                          },
                        ],
                        children: (resolvedLinks1) =>
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 21,
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-3lob3f-container",
                                layoutDependency: layoutDependency,
                                layoutId: "x7C5iuwDJ-container",
                                nodeId: "x7C5iuwDJ",
                                rendersWithMotion: true,
                                scopeId: "CbPIrLAGo",
                                children: /*#__PURE__*/ _jsx(Link1, {
                                  height: "100%",
                                  id: "x7C5iuwDJ",
                                  layoutId: "x7C5iuwDJ",
                                  QDl07_yb4: "Terms & Conditions",
                                  width: "100%",
                                  XakXd1OLN: resolvedLinks1[0],
                                  ...addPropertyOverrides(
                                    {
                                      ajxLpnJUX: {
                                        XakXd1OLN: resolvedLinks1[1],
                                      },
                                      VJeGkoAO8: {
                                        XakXd1OLN: resolvedLinks1[2],
                                      },
                                    },
                                    baseVariant,
                                    gestureVariant
                                  ),
                                }),
                              }
                            ),
                          }),
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-mfTJr.framer-1qq85lr, .framer-mfTJr .framer-1qq85lr { display: block; }",
  ".framer-mfTJr.framer-9ih1cv { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px 30px 40px 30px; position: relative; width: 1200px; }",
  ".framer-mfTJr .framer-wp98lf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 100px; height: min-content; justify-content: center; max-width: 1170px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-mfTJr .framer-2s24gv { -webkit-user-select: none; aspect-ratio: 0.8592233009708737 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 206px); left: 90%; position: absolute; top: -8%; user-select: none; width: 16%; }",
  ".framer-mfTJr .framer-rtlp78 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 30px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-mfTJr .framer-t8qkff { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 70px 30px 70px 30px; position: relative; width: 1px; }",
  ".framer-mfTJr .framer-p8nw3y { -webkit-user-select: none; aspect-ratio: 2.8947368421052633 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 19px); left: 91%; overflow: visible; pointer-events: none; position: absolute; top: 21%; user-select: none; width: 5%; }",
  ".framer-mfTJr .framer-1fxb95w { -webkit-user-select: none; aspect-ratio: 2.8947368421052633 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 19px); left: 75%; overflow: visible; pointer-events: none; position: absolute; top: 69%; user-select: none; width: 5%; }",
  ".framer-mfTJr .framer-kf7dxg { -webkit-user-select: none; aspect-ratio: 3.522727272727273 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 47px); left: 89%; overflow: visible; pointer-events: none; position: absolute; top: 81%; user-select: none; width: 15%; }",
  ".framer-mfTJr .framer-4p13sd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-mfTJr .framer-3wqid8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-mfTJr .framer-1bnzlos, .framer-mfTJr .framer-1adt9ib { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-mfTJr .framer-1t7y4n4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 14px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-mfTJr .framer-13jbem0-container, .framer-mfTJr .framer-1ecko0-container, .framer-mfTJr .framer-1cmcmhf-container, .framer-mfTJr .framer-1dvpbt9-container, .framer-mfTJr .framer-6i0aye-container, .framer-mfTJr .framer-3lob3f-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-mfTJr .framer-ifmgpy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-mfTJr .framer-1w1nrx5 { -webkit-user-select: none; aspect-ratio: 1.3210332103321034 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 276px); left: 16%; position: absolute; top: 65%; user-select: none; width: 32%; }",
  ".framer-mfTJr .framer-dkonb2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 18px 32px 18px 32px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-mfTJr .framer-nngp5w { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-mfTJr .framer-145e5ss-container { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; width: auto; }",
  ".framer-mfTJr .framer-1kjbwxc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-mfTJr .framer-hwjnl { -webkit-user-select: none; flex: none; gap: 10px; height: 19px; overflow: hidden; position: relative; user-select: none; width: 1px; }",
  ".framer-mfTJr.framer-v-1oitkep.framer-9ih1cv { width: 810px; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-wp98lf { gap: 60px; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-2s24gv { height: var(--framer-aspect-ratio-supported, 136px); }",
  ".framer-mfTJr.framer-v-1oitkep .framer-t8qkff { padding: 60px 30px 60px 30px; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-p8nw3y { height: var(--framer-aspect-ratio-supported, 12px); }",
  ".framer-mfTJr.framer-v-1oitkep .framer-1fxb95w, .framer-mfTJr.framer-v-hav8xk .framer-kf7dxg { height: var(--framer-aspect-ratio-supported, 13px); }",
  ".framer-mfTJr.framer-v-1oitkep .framer-kf7dxg { height: var(--framer-aspect-ratio-supported, 30px); }",
  ".framer-mfTJr.framer-v-1oitkep .framer-4p13sd { gap: 32px; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-1w1nrx5 { height: var(--framer-aspect-ratio-supported, 182px); }",
  ".framer-mfTJr.framer-v-1oitkep .framer-dkonb2 { flex-direction: column; gap: 16px; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-nngp5w, .framer-mfTJr.framer-v-hav8xk .framer-nngp5w { flex: none; width: 100%; }",
  ".framer-mfTJr.framer-v-1oitkep .framer-1kjbwxc, .framer-mfTJr.framer-v-hav8xk .framer-1kjbwxc { flex: none; justify-content: center; width: 100%; }",
  ".framer-mfTJr.framer-v-hav8xk.framer-9ih1cv { padding: 0px 20px 40px 20px; width: 390px; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-wp98lf { gap: 40px; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-2s24gv { height: var(--framer-aspect-ratio-supported, 127px); left: 95%; top: -6%; width: 31%; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-rtlp78 { padding: 20px; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-t8qkff { padding: 60px 20px 60px 20px; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-p8nw3y, .framer-mfTJr.framer-v-hav8xk .framer-1fxb95w { height: var(--framer-aspect-ratio-supported, 6px); }",
  ".framer-mfTJr.framer-v-hav8xk .framer-4p13sd { gap: 24px; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-1t7y4n4 { flex-direction: column; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-1w1nrx5 { height: var(--framer-aspect-ratio-supported, 128px); left: 24%; top: 61%; width: 48%; }",
  ".framer-mfTJr.framer-v-hav8xk .framer-dkonb2 { flex-direction: column; gap: 16px; padding: 30px 32px 30px 32px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  '.framer-mfTJr[data-border="true"]::after, .framer-mfTJr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 682.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ajxLpnJUX":{"layout":["fixed","auto"]},"VJeGkoAO8":{"layout":["fixed","auto"]}}}
 * @framerVariables {"QirT5gtEY":"logoLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerCbPIrLAGo = withCSS(Component, css, "framer-mfTJr");
export default FramerCbPIrLAGo;
FramerCbPIrLAGo.displayName = "Footer";
FramerCbPIrLAGo.defaultProps = { height: 682.5, width: 1200 };
addPropertyControls(FramerCbPIrLAGo, {
  variant: {
    options: ["xJvyj9BDJ", "ajxLpnJUX", "VJeGkoAO8"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  QirT5gtEY: { title: "Logo Link", type: ControlType.Link },
});
addFonts(
  FramerCbPIrLAGo,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ButtonFonts,
    ...SocialLinkFonts,
    ...LogoFonts,
    ...Link1Fonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerCbPIrLAGo",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "682.5",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "1200",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ajxLpnJUX":{"layout":["fixed","auto"]},"VJeGkoAO8":{"layout":["fixed","auto"]}}}',
        framerVariables: '{"QirT5gtEY":"logoLink"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./CbPIrLAGo.map
