// Generated by Framer (9f1494d)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/5bdfLqH6lT8T5xf4GMV4/1JdpUmOMiu0WMRRWpxBJ/m8DU6sDyG.js";
const enabledGestures = {
  u9cHE4zsd: { hover: true },
  W4jjelGVX: { hover: true },
};
const cycleOrder = ["u9cHE4zsd", "W4jjelGVX"];
const serializationHash = "framer-dIqKk";
const variantClassNames = {
  u9cHE4zsd: "framer-v-9tv1lx",
  W4jjelGVX: "framer-v-8t0lri",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const animation = {
  filter: "blur(10px)",
  opacity: 0.001,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 10,
};
const transition2 = { bounce: 0, delay: 0.05, duration: 0.4, type: "spring" };
const textEffect = {
  effect: animation,
  tokenization: "character",
  transition: transition2,
  trigger: "onInView",
  type: "appear",
};
const textEffect1 = {
  effect: animation,
  repeat: false,
  startDelay: 0,
  threshold: 0,
  tokenization: "character",
  transition: transition2,
  trigger: "onInView",
  type: "appear",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Default: "u9cHE4zsd", Large: "W4jjelGVX" };
const getProps = ({ height, id, link, newTab, text, width, ...props }) => {
  return {
    ...props,
    MKPg9WbcL: text ?? props.MKPg9WbcL ?? "Buy Now",
    QUXmHzKkq: newTab ?? props.QUXmHzKkq,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "u9cHE4zsd",
    VZYEYY3gb: link ?? props.VZYEYY3gb,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    MKPg9WbcL,
    VZYEYY3gb,
    QUXmHzKkq,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "u9cHE4zsd",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["u9cHE4zsd-hover", "W4jjelGVX-hover"].includes(gestureVariant))
      return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: VZYEYY3gb,
          motionChild: true,
          nodeId: "u9cHE4zsd",
          openInNewTab: QUXmHzKkq,
          scopeId: "Dc_z1yLfb",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-9tv1lx",
              className,
              classNames
            )} framer-p2v4t8`,
            "data-framer-name": "Default",
            layoutDependency: layoutDependency,
            layoutId: "u9cHE4zsd",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              {
                "u9cHE4zsd-hover": { "data-framer-name": undefined },
                "W4jjelGVX-hover": { "data-framer-name": undefined },
                W4jjelGVX: { "data-framer-name": "Large" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "BG",
                  fit: "fill",
                  intrinsicHeight: 51,
                  intrinsicWidth: 115,
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) + 0
                  ),
                  pixelHeight: 53,
                  pixelWidth: 116,
                  src: "https://framerusercontent.com/images/IGR1GmycrguEKnrxTzb7GR3yi0.svg",
                },
                className: "framer-5rqbj2",
                "data-framer-name": "BG",
                layoutDependency: layoutDependency,
                layoutId: "GXvUE4aT7",
                ...addPropertyOverrides(
                  {
                    W4jjelGVX: {
                      background: {
                        alt: "BG",
                        fit: "fill",
                        intrinsicHeight: 51,
                        intrinsicWidth: 115,
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + 0
                        ),
                        pixelHeight: 54,
                        pixelWidth: 179,
                        src: "https://framerusercontent.com/images/Od6C2Y5ysZrhIwO05VHQwUtU0YM.svg",
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1gou2ux",
                    "data-styles-preset": "m8DU6sDyG",
                    children: "Buy Now",
                  }),
                }),
                className: "framer-1i5ywuk",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "kIyCfOYQX",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                  "--framer-paragraph-spacing": "0px",
                  opacity: 1,
                },
                text: MKPg9WbcL,
                variants: {
                  "u9cHE4zsd-hover": { opacity: 0 },
                  "W4jjelGVX-hover": { opacity: 0 },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              isDisplayed() &&
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1gou2ux",
                      "data-styles-preset": "m8DU6sDyG",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61)))",
                      },
                      children: "Buy Now",
                    }),
                  }),
                  className: "framer-6iu5t4",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "o2GeHavzR",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: MKPg9WbcL,
                  transformTemplate: transformTemplate1,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      "u9cHE4zsd-hover": { effect: textEffect },
                      "W4jjelGVX-hover": { effect: textEffect1 },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-dIqKk.framer-p2v4t8, .framer-dIqKk .framer-p2v4t8 { display: block; }",
  ".framer-dIqKk.framer-9tv1lx { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 16px 20px 15px 20px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-dIqKk .framer-5rqbj2 { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; user-select: none; }",
  ".framer-dIqKk .framer-1i5ywuk { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-dIqKk .framer-6iu5t4 { -webkit-user-select: none; flex: none; height: auto; left: 50%; position: absolute; top: 49%; user-select: none; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-dIqKk.framer-9tv1lx { gap: 0px; } .framer-dIqKk.framer-9tv1lx > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-dIqKk.framer-9tv1lx > :first-child { margin-left: 0px; } .framer-dIqKk.framer-9tv1lx > :last-child { margin-right: 0px; } }",
  ".framer-dIqKk.framer-v-8t0lri.framer-9tv1lx { padding: 15px 26px 15px 26px; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 52.5
 * @framerIntrinsicWidth 116.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"W4jjelGVX":{"layout":["auto","auto"]},"hC_lXYCPs":{"layout":["auto","auto"]},"UyNhGTkgw":{"layout":["auto","auto"]}}}
 * @framerVariables {"MKPg9WbcL":"text","VZYEYY3gb":"link","QUXmHzKkq":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerDc_z1yLfb = withCSS(Component, css, "framer-dIqKk");
export default FramerDc_z1yLfb;
FramerDc_z1yLfb.displayName = "Button";
FramerDc_z1yLfb.defaultProps = { height: 52.5, width: 116.5 };
addPropertyControls(FramerDc_z1yLfb, {
  variant: {
    options: ["u9cHE4zsd", "W4jjelGVX"],
    optionTitles: ["Default", "Large"],
    title: "Variant",
    type: ControlType.Enum,
  },
  MKPg9WbcL: {
    defaultValue: "Buy Now",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  VZYEYY3gb: { title: "Link", type: ControlType.Link },
  QUXmHzKkq: {
    defaultValue: false,
    title: "New Tab",
    type: ControlType.Boolean,
  },
});
addFonts(
  FramerDc_z1yLfb,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerDc_z1yLfb",
      slots: [],
      annotations: {
        framerVariables:
          '{"MKPg9WbcL":"text","VZYEYY3gb":"link","QUXmHzKkq":"newTab"}',
        framerIntrinsicHeight: "52.5",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "116.5",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"W4jjelGVX":{"layout":["auto","auto"]},"hC_lXYCPs":{"layout":["auto","auto"]},"UyNhGTkgw":{"layout":["auto","auto"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./Dc_z1yLfb.map
