// Generated by Framer (beb597f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/w4lD9QCTXNcSaJcap9cr/i7aShT66aHqJ8TpzpvmH/IC8d9vcch.js";
import * as sharedStyle1 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/6LEKNaYv1cfPWq4rs2JS/Gw1WsjsGUwFWX9MMUpxk/Mm7k0zH8w.js";
import * as sharedStyle2 from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/A4Rhs3kfCcK6G7a277fz/6G8xZ9mzCiymva6SzShu/VgWUtp2Rd.js";
const cycleOrder = ["ctx6qTYdF", "VTmBsvDf5", "d_SelHgg8"];
const serializationHash = "framer-BRF8N";
const variantClassNames = {
  ctx6qTYdF: "framer-v-1rj1vpy",
  d_SelHgg8: "framer-v-1x6apax",
  VTmBsvDf5: "framer-v-1wjo43v",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const m8Q8du1aR = undefined;
const ron1uubmi = undefined;
const bOsVYIAN7 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 01": "ctx6qTYdF",
  "Variant 02": "VTmBsvDf5",
  "Variant 03": "d_SelHgg8",
};
const getProps = ({ height, icon, id, subtitle, title, width, ...props }) => {
  return {
    ...props,
    bOsVYIAN7:
      subtitle ?? props.bOsVYIAN7 ?? "Download MetaMask or Trust Wallet.",
    m8Q8du1aR: icon ??
      props.m8Q8du1aR ?? {
        pixelHeight: 51,
        pixelWidth: 50,
        src: "https://framerusercontent.com/images/CobVD6r6dvZJkGMaFH9zJoeq7Ec.png?width=50&height=51",
      },
    ron1uubmi: title ?? props.ron1uubmi ?? "Get a Wallet",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "ctx6qTYdF",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    m8Q8du1aR,
    ron1uubmi,
    bOsVYIAN7,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "ctx6qTYdF",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1rj1vpy",
            className,
            classNames
          ),
          "data-framer-name": "Variant 01",
          layoutDependency: layoutDependency,
          layoutId: "ctx6qTYdF",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              d_SelHgg8: { "data-framer-name": "Variant 03" },
              VTmBsvDf5: { "data-framer-name": "Variant 02" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(Image, {
              "aria-label": "BG",
              className: "framer-mrz79g",
              "data-border": true,
              "data-framer-name": "BG",
              layoutDependency: layoutDependency,
              layoutId: "jUdBOQHyp",
              style: {
                "--border-bottom-width": "2px",
                "--border-color":
                  "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                "--border-left-width": "2px",
                "--border-right-width": "2px",
                "--border-style": "solid",
                "--border-top-width": "2px",
                backgroundColor:
                  "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                borderBottomLeftRadius: 16,
                borderBottomRightRadius: 16,
                borderTopLeftRadius: 16,
                borderTopRightRadius: 16,
                boxShadow: "none",
              },
              variants: {
                d_SelHgg8: {
                  boxShadow:
                    "0px 4px 0px 0px var(--token-ebf707e2-9a0d-49da-bcbe-2b81e97334fa, rgb(0, 0, 0))",
                },
                VTmBsvDf5: {
                  "--border-bottom-width": "0px",
                  "--border-left-width": "0px",
                  "--border-right-width": "0px",
                  "--border-top-width": "0px",
                  backgroundColor: "rgba(0, 0, 0, 0)",
                  borderBottomLeftRadius: 0,
                  borderBottomRightRadius: 0,
                  borderTopLeftRadius: 0,
                  borderTopRightRadius: 0,
                },
              },
              ...addPropertyOverrides(
                {
                  VTmBsvDf5: {
                    "aria-label": undefined,
                    background: {
                      alt: "BG",
                      fit: "fill",
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) + 0
                      ),
                      pixelHeight: 1328,
                      pixelWidth: 1717,
                      sizes: componentViewport?.width || "100vw",
                      src: "https://framerusercontent.com/images/IwuP2iAAV5vSGDJSDDCUxvAjURo.png?width=1717&height=1328",
                      srcSet:
                        "https://framerusercontent.com/images/IwuP2iAAV5vSGDJSDDCUxvAjURo.png?scale-down-to=512&width=1717&height=1328 512w,https://framerusercontent.com/images/IwuP2iAAV5vSGDJSDDCUxvAjURo.png?scale-down-to=1024&width=1717&height=1328 1024w,https://framerusercontent.com/images/IwuP2iAAV5vSGDJSDDCUxvAjURo.png?width=1717&height=1328 1717w",
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-mjmush",
              "data-framer-name": "Icon Box",
              layoutDependency: layoutDependency,
              layoutId: "zY1leNLEz",
              style: {
                "--border-bottom-width": "0px",
                "--border-color": "rgba(0, 0, 0, 0)",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-style": "solid",
                "--border-top-width": "0px",
                backgroundColor: "rgba(0, 0, 0, 0)",
                borderBottomLeftRadius: 0,
                borderBottomRightRadius: 0,
                borderTopLeftRadius: 0,
                borderTopRightRadius: 0,
              },
              variants: {
                d_SelHgg8: {
                  "--border-bottom-width": "2px",
                  "--border-color":
                    "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                  "--border-left-width": "2px",
                  "--border-right-width": "2px",
                  "--border-style": "solid",
                  "--border-top-width": "2px",
                  backgroundColor:
                    "var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, rgb(255, 255, 255))",
                  borderBottomLeftRadius: "100%",
                  borderBottomRightRadius: "100%",
                  borderTopLeftRadius: "100%",
                  borderTopRightRadius: "100%",
                },
              },
              ...addPropertyOverrides(
                {
                  d_SelHgg8: {
                    "data-border": true,
                    transformTemplate: transformTemplate1,
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(Image, {
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(
                    (componentViewport?.y || 0) +
                      30 +
                      (((componentViewport?.height || 223) - 60 - 297.6) / 2 +
                        0 +
                        0) +
                      0
                  ),
                  pixelHeight: 51,
                  pixelWidth: 50,
                  sizes: "50px",
                  ...toResponsiveImage(m8Q8du1aR),
                },
                className: "framer-zht7th",
                "data-framer-name": "Icon",
                layoutDependency: layoutDependency,
                layoutId: "Tpj5jxqKz",
                ...addPropertyOverrides(
                  {
                    d_SelHgg8: {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) + -40 + 18
                        ),
                        pixelHeight: 51,
                        pixelWidth: 50,
                        sizes: "45px",
                        ...toResponsiveImage(m8Q8du1aR),
                      },
                    },
                    VTmBsvDf5: {
                      background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(
                          (componentViewport?.y || 0) +
                            50 +
                            (((componentViewport?.height || 267.5) -
                              100 -
                              268.4) /
                              2 +
                              0 +
                              0) +
                            0
                        ),
                        pixelHeight: 51,
                        pixelWidth: 50,
                        sizes: "50px",
                        ...toResponsiveImage(m8Q8du1aR),
                      },
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1srkjva",
              "data-framer-name": "Title",
              layoutDependency: layoutDependency,
              layoutId: "H2t0EJwZG",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h3, {
                      className: "framer-styles-preset-16auejx",
                      "data-styles-preset": "IC8d9vcch",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-a0htzi, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                      },
                      children: "Get a Wallet",
                    }),
                  }),
                  className: "framer-1ay6144",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "NxXULjUWT",
                  style: {
                    "--extracted-a0htzi":
                      "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: ron1uubmi,
                  variants: {
                    VTmBsvDf5: {
                      "--extracted-1eung3n":
                        "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    },
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      d_SelHgg8: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            className: "framer-styles-preset-16auejx",
                            "data-styles-preset": "IC8d9vcch",
                            style: {
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-a0htzi, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                            },
                            children: "Get a Wallet",
                          }),
                        }),
                      },
                      VTmBsvDf5: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h4, {
                            className: "framer-styles-preset-rvsjv3",
                            "data-styles-preset": "Mm7k0zH8w",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-1eung3n, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                            },
                            children: "Get a Wallet",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-n1xc3h",
                      "data-styles-preset": "VgWUtp2Rd",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                      },
                      children: "Download MetaMask or Trust Wallet.",
                    }),
                  }),
                  className: "framer-1wmdpfr",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "lI7irzyxm",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24))",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: bOsVYIAN7,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides(
                    {
                      d_SelHgg8: {
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-n1xc3h",
                            "data-styles-preset": "VgWUtp2Rd",
                            style: {
                              "--framer-text-alignment": "center",
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, rgb(16, 12, 24)))",
                            },
                            children: "Download MetaMask or Trust Wallet.",
                          }),
                        }),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-BRF8N.framer-1r01h6u, .framer-BRF8N .framer-1r01h6u { display: block; }",
  ".framer-BRF8N.framer-1rj1vpy { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 30px; position: relative; width: 520px; }",
  ".framer-BRF8N .framer-mrz79g { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; user-select: none; }",
  ".framer-BRF8N .framer-mjmush { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-BRF8N .framer-zht7th { -webkit-user-select: none; aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 50px); overflow: hidden; position: relative; user-select: none; width: 50px; will-change: var(--framer-will-change-filter-override, filter); }",
  ".framer-BRF8N .framer-1srkjva { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-BRF8N .framer-1ay6144, .framer-BRF8N .framer-1wmdpfr { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-BRF8N.framer-v-1wjo43v.framer-1rj1vpy { aspect-ratio: 1.2883895131086143 / 1; gap: 16px; height: var(--framer-aspect-ratio-supported, 268px); padding: 50px 30px 50px 30px; width: 340px; }",
  ".framer-BRF8N.framer-v-1wjo43v .framer-1srkjva { gap: 8px; }",
  ".framer-BRF8N.framer-v-1x6apax.framer-1rj1vpy { align-content: center; align-items: center; padding: 80px 30px 30px 30px; }",
  ".framer-BRF8N.framer-v-1x6apax .framer-mjmush { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 76px); left: 50%; position: absolute; top: -40px; width: 76px; }",
  ".framer-BRF8N.framer-v-1x6apax .framer-zht7th { height: var(--framer-aspect-ratio-supported, 45px); width: 45px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  '.framer-BRF8N[data-border="true"]::after, .framer-BRF8N [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 223
 * @framerIntrinsicWidth 520
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VTmBsvDf5":{"layout":["fixed","fixed"]},"d_SelHgg8":{"layout":["fixed","auto"]}}}
 * @framerVariables {"m8Q8du1aR":"icon","ron1uubmi":"title","bOsVYIAN7":"subtitle"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerkf32jfKvC = withCSS(Component, css, "framer-BRF8N");
export default Framerkf32jfKvC;
Framerkf32jfKvC.displayName = "Single Buy";
Framerkf32jfKvC.defaultProps = { height: 223, width: 520 };
addPropertyControls(Framerkf32jfKvC, {
  variant: {
    options: ["ctx6qTYdF", "VTmBsvDf5", "d_SelHgg8"],
    optionTitles: ["Variant 01", "Variant 02", "Variant 03"],
    title: "Variant",
    type: ControlType.Enum,
  },
  m8Q8du1aR: {
    __defaultAssetReference:
      "data:framer/asset-reference,CobVD6r6dvZJkGMaFH9zJoeq7Ec.png?originalFilename=Unknown.png&width=50&height=51",
    title: "Icon",
    type: ControlType.ResponsiveImage,
  },
  ron1uubmi: {
    defaultValue: "Get a Wallet",
    displayTextArea: true,
    title: "Title",
    type: ControlType.String,
  },
  bOsVYIAN7: {
    defaultValue: "Download MetaMask or Trust Wallet.",
    displayTextArea: true,
    title: "Subtitle",
    type: ControlType.String,
  },
});
addFonts(
  Framerkf32jfKvC,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerkf32jfKvC",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "520",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerVariables:
          '{"m8Q8du1aR":"icon","ron1uubmi":"title","bOsVYIAN7":"subtitle"}',
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"VTmBsvDf5":{"layout":["fixed","fixed"]},"d_SelHgg8":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "223",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./kf32jfKvC.map
