// Generated by Framer (beb597f)
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "1nazja9", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "1yv3c46",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "1x51cap", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: "Before the alpha, before the wins, there was n00b.",
    elements: { C01TUQU7_: "hero", n8EtdoyqS: "buy" },
    framerSearch: { index: true },
    robots: "max-image-preview:large",
    serializationId: "framer-lAGJH",
    title: "NOOB",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
