// Generated by Framer (9d598a4)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-wCCxa .framer-styles-preset-s58osx:not(.rich-text-wrapper), .framer-wCCxa .framer-styles-preset-s58osx.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-1f541b1a-683e-4348-b126-ecf96487958f, #38963d); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-fbaaa515-886b-4f1c-9cc2-16c4b4d7a23e, #100c18); --framer-link-text-decoration: none; transition: color 0.4s cubic-bezier(0.44, 0, 0.56, 1) 0s; }",
];
export const className = "framer-wCCxa";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
