// Generated by Framer (9f1494d)
import { fontStore } from "framer";
fontStore.loadFonts(["GF;Luckiest Guy-regular"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Luckiest Guy",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/luckiestguy/v23/_gP_1RrxsjcxVyin9l9n_j2RT9R3qDpraA.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  '.framer-DXR5E .framer-styles-preset-rvsjv3:not(.rich-text-wrapper), .framer-DXR5E .framer-styles-preset-rvsjv3.rich-text-wrapper h4 { --framer-font-family: "Luckiest Guy", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.1em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-DXR5E .framer-styles-preset-rvsjv3:not(.rich-text-wrapper), .framer-DXR5E .framer-styles-preset-rvsjv3.rich-text-wrapper h4 { --framer-font-family: "Luckiest Guy", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.1em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-DXR5E .framer-styles-preset-rvsjv3:not(.rich-text-wrapper), .framer-DXR5E .framer-styles-preset-rvsjv3.rich-text-wrapper h4 { --framer-font-family: "Luckiest Guy", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.1em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-28ef2359-faf3-4a1d-aaab-09bbf4529e7c, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
export const className = "framer-DXR5E";
export const __FramerMetadata__ = {
  exports: {
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
