// Generated by Framer (beb597f)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  Container,
  ControlType,
  cx,
  GeneratedComponentContext,
  getFonts,
  PropertyOverrides,
  RenderTarget,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  withCSS,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Footer from "#framer/local/canvasComponent/CbPIrLAGo/CbPIrLAGo.js";
import Header from "#framer/local/canvasComponent/xvq9ojUUg/xvq9ojUUg.js";
const HeaderFonts = getFonts(Header);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const FooterFonts = getFonts(Footer);
const breakpoints = {
  KdVnqVg7z: "(min-width: 810px) and (max-width: 1199.98px)",
  PGxJdUmEo: "(max-width: 809.98px)",
  Wy61cjCPn: "(min-width: 1200px)",
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-NPCvn";
const variantClassNames = {
  KdVnqVg7z: "framer-v-1dfkmv1",
  PGxJdUmEo: "framer-v-o3985",
  Wy61cjCPn: "framer-v-u2y368",
};
const wcNfTqjf4 = undefined;
const kpmHBdXdi = undefined;
const qPl23R2jN = undefined;
const EoyjD5jyL = undefined;
const transition1 = {
  damping: 60,
  delay: 0.2,
  mass: 1,
  stiffness: 400,
  type: "spring",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: -100,
};
const breakpointRules = {};
const breakpointKeys = Object.keys(breakpointRules);
const rules = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-NPCvn.framer-1kzwxkk, .framer-NPCvn .framer-1kzwxkk { display: block; }",
  ".framer-NPCvn.framer-u2y368 { align-content: center; align-items: center; background-color: var(--token-1f541b1a-683e-4348-b126-ecf96487958f, #38963d); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-NPCvn .framer-1h4nik0-container { flex: none; height: auto; left: 0px; order: -1000; position: var(--framer-canvas-fixed-position, fixed); right: 0px; top: 0px; will-change: var(--framer-will-change-effect-override, transform); z-index: 8; }",
  ".framer-NPCvn .framer-1qxaewl { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }",
  ".framer-NPCvn .framer-14q17nx-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }",
  '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }',
];
const mediaQueries = {
  KdVnqVg7z: "(min-width: 810px) and (max-width: 1199.98px)",
  PGxJdUmEo: "(max-width: 809.98px)",
  Wy61cjCPn: "(min-width: 1200px)",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const humanReadableVariantMap = {
  Desktop: "Wy61cjCPn",
  Phone: "PGxJdUmEo",
  Tablet: "KdVnqVg7z",
};
const getProps = ({
  footerButtonLink,
  footerLogoLink,
  headerButtonLink,
  headerLogoLink,
  height,
  id,
  width,
  ...props
}) => {
  return {
    ...props,
    EoyjD5jyL: footerButtonLink ?? props.EoyjD5jyL,
    kpmHBdXdi: headerButtonLink ?? props.kpmHBdXdi,
    qPl23R2jN: footerLogoLink ?? props.qPl23R2jN,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Wy61cjCPn",
    wcNfTqjf4: headerLogoLink ?? props.wcNfTqjf4,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    wcNfTqjf4,
    kpmHBdXdi,
    qPl23R2jN,
    EoyjD5jyL,
    children,
    ...restProps
  } = getProps(props);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      isLayoutTemplate: true,
      primaryVariantId: "Wy61cjCPn",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            ":root body { background: var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(56, 150, 61)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-u2y368", className),
          "data-layout-template": true,
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 130,
              width: "100vw",
              y: 0,
              children: /*#__PURE__*/ _jsx(ContainerWithOptimizedAppearEffect, {
                animate: animation,
                className: "framer-1h4nik0-container",
                "data-framer-appear-id": "1h4nik0",
                initial: animation1,
                layoutScroll: true,
                nodeId: "C7RkG8m9f",
                optimized: true,
                rendersWithMotion: true,
                scopeId: "jK69qE2N9",
                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: { PGxJdUmEo: { variant: "RlvGJyhCo" } },
                  children: /*#__PURE__*/ _jsx(Header, {
                    height: "100%",
                    id: "C7RkG8m9f",
                    layoutId: "C7RkG8m9f",
                    nwZU2ETO3: kpmHBdXdi,
                    qUsgEym5f: wcNfTqjf4,
                    style: { width: "100%" },
                    variant: "dKLcsb4Hw",
                    width: "100%",
                  }),
                }),
              }),
            }),
            children,
            /*#__PURE__*/ _jsx("div", { className: "framer-1qxaewl" }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 653,
              width: "100vw",
              y: 1e3,
              children: /*#__PURE__*/ _jsx(Container, {
                className: "framer-14q17nx-container",
                nodeId: "ClmrdTZCm",
                scopeId: "jK69qE2N9",
                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    KdVnqVg7z: { variant: "ajxLpnJUX" },
                    PGxJdUmEo: { variant: "VJeGkoAO8" },
                  },
                  children: /*#__PURE__*/ _jsx(Footer, {
                    height: "100%",
                    id: "ClmrdTZCm",
                    layoutId: "ClmrdTZCm",
                    QirT5gtEY: qPl23R2jN,
                    style: { width: "100%" },
                    variant: "xJvyj9BDJ",
                    width: "100%",
                    yO1oc5h3m: EoyjD5jyL,
                  }),
                }),
              }),
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "template-overlay" }),
      ],
    }),
  });
});
const css = (target) => {
  const isStaticRenderer =
    target === RenderTarget.canvas || target === RenderTarget.export;
  if (!isStaticRenderer) {
    return [
      ...rules,
      ...breakpointKeys.map((key) => {
        const query = mediaQueries[key];
        return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
      }),
    ];
  }
  return [
    ...rules,
    ...breakpointKeys.flatMap((key) => {
      const selector = breakpointRules[key];
      return breakpointRules[key].map((rule) => `${selector} {${rule}}`);
    }),
  ];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1249
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"KdVnqVg7z":{"layout":["fixed","fixed"]},"PGxJdUmEo":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"wcNfTqjf4":"headerLogoLink","kpmHBdXdi":"headerButtonLink","qPl23R2jN":"footerLogoLink","EoyjD5jyL":"footerButtonLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"Wy61cjCPn":[".framer-1h4nik0-container",".framer-14q17nx-container"],"KdVnqVg7z":[".framer-1h4nik0-container",".framer-14q17nx-container"],"PGxJdUmEo":[".framer-1h4nik0-container",".framer-14q17nx-container"]}
 * @framerBreakpoints {"Wy61cjCPn":{"min":1200,"canvasClassName":"framer-u2y368-override","minHeight":1249,"name":"Desktop","width":1200,"rootFontSize":16},"KdVnqVg7z":{"min":810,"max":1199,"canvasClassName":"framer-1dfkmv1-override","minHeight":1249,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"PGxJdUmEo":{"max":809,"canvasClassName":"framer-o3985-override","minHeight":1249,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant Wy61cjCPn
 * @framerLayoutTemplate true
 */ const FramerjK69qE2N9 = withCSS(Component, css, "framer-NPCvn");
export default FramerjK69qE2N9;
FramerjK69qE2N9.displayName = "Default";
FramerjK69qE2N9.defaultProps = { height: 1249, width: 1200 };
addPropertyControls(FramerjK69qE2N9, {
  wcNfTqjf4: { title: "Header - Logo Link", type: ControlType.Link },
  kpmHBdXdi: { title: "Header - Button Link", type: ControlType.Link },
  qPl23R2jN: { title: "Footer - Logo Link", type: ControlType.Link },
  EoyjD5jyL: { title: "Footer - Button Link", type: ControlType.Link },
});
addFonts(
  FramerjK69qE2N9,
  [{ explicitInter: true, fonts: [] }, ...HeaderFonts, ...FooterFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerjK69qE2N9",
      slots: [],
      annotations: {
        framerBreakpoints:
          '{"Wy61cjCPn":{"min":1200,"canvasClassName":"framer-u2y368-override","minHeight":1249,"name":"Desktop","width":1200,"rootFontSize":16},"KdVnqVg7z":{"min":810,"max":1199,"canvasClassName":"framer-1dfkmv1-override","minHeight":1249,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"PGxJdUmEo":{"max":809,"canvasClassName":"framer-o3985-override","minHeight":1249,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}',
        framerIntrinsicHeight: "1249",
        framerColorSyntax: "true",
        framerVariables:
          '{"wcNfTqjf4":"headerLogoLink","kpmHBdXdi":"headerButtonLink","qPl23R2jN":"footerLogoLink","EoyjD5jyL":"footerButtonLink"}',
        framerIntrinsicWidth: "1200",
        framerContractVersion: "1",
        framerDefaultVariant: "Wy61cjCPn",
        framerLayoutTemplate: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"KdVnqVg7z":{"layout":["fixed","fixed"]},"PGxJdUmEo":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerHitTargets:
          '{"Wy61cjCPn":[".framer-1h4nik0-container",".framer-14q17nx-container"],"KdVnqVg7z":[".framer-1h4nik0-container",".framer-14q17nx-container"],"PGxJdUmEo":[".framer-1h4nik0-container",".framer-14q17nx-container"]}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
