// Generated by Framer (beb597f)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  cx,
  getFonts,
  Image,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Ticker from "../framerusercontent/sites/3Xsw28p3gOgyXOHwGO3PsA/https/framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/jyRNgY7vYWXe6t31T0wo/Ticker.js";
const TickerFonts = getFonts(Ticker);
const serializationHash = "framer-Pye6k";
const variantClassNames = { ANXoztmw3: "framer-v-51xvcq" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "ANXoztmw3",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-51xvcq",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "ANXoztmw3",
          ref: refBinding,
          style: {
            "--border-bottom-width": "3px",
            "--border-color":
              "var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204))",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "3px",
            backgroundColor:
              "var(--token-3b2f3565-92cd-4dd6-8226-6bb578df41c1, rgb(255, 255, 255))",
            boxShadow:
              "inset 0px 2.67px 0px 1.78px var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204)), 0px 6px 0px 0px var(--token-1f541b1a-683e-4348-b126-ecf96487958f, rgb(96, 199, 204))",
            ...style,
          },
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-13xmyd4-container",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "yQrOF3rHM-container",
              nodeId: "yQrOF3rHM",
              rendersWithMotion: true,
              scopeId: "uoXiGtpFK",
              children: /*#__PURE__*/ _jsx(Ticker, {
                alignment: "center",
                direction: "left",
                fadeOptions: {
                  fadeAlpha: 0,
                  fadeContent: false,
                  fadeInset: 0,
                  fadeWidth: 25,
                  overflow: false,
                },
                gap: 32,
                height: "100%",
                hoverFactor: 1,
                id: "yQrOF3rHM",
                layoutId: "yQrOF3rHM",
                padding: 0,
                paddingBottom: 0,
                paddingLeft: 0,
                paddingPerSide: false,
                paddingRight: 0,
                paddingTop: 0,
                sizingOptions: { heightType: true, widthType: true },
                slots: [
                  /*#__PURE__*/ _jsx(Image, {
                    background: {
                      alt: "Logo",
                      fit: "fill",
                      pixelHeight: 286,
                      pixelWidth: 1095,
                      sizes: "147px",
                      src: "https://framerusercontent.com/images/etqQVAqU0VgRLSgjmAVo7eZ8rLk.png?width=1095&height=286",
                      srcSet:
                        "https://framerusercontent.com/images/etqQVAqU0VgRLSgjmAVo7eZ8rLk.png?scale-down-to=512&width=1095&height=286 512w,https://framerusercontent.com/images/etqQVAqU0VgRLSgjmAVo7eZ8rLk.png?scale-down-to=1024&width=1095&height=286 1024w,https://framerusercontent.com/images/etqQVAqU0VgRLSgjmAVo7eZ8rLk.png?width=1095&height=286 1095w",
                    },
                    className: "framer-pan9ol",
                    "data-framer-name": "Logo",
                    layoutDependency: layoutDependency,
                    layoutId: "iy002lUyl",
                  }),
                ],
                speed: 50,
                style: { height: "100%", width: "100%" },
                width: "100%",
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Pye6k.framer-qce24z, .framer-Pye6k .framer-qce24z { display: block; }",
  ".framer-Pye6k.framer-51xvcq { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 24px 0px; position: relative; width: 1140px; }",
  ".framer-Pye6k .framer-13xmyd4-container { flex: 1 0 0px; height: 40px; position: relative; width: 1px; }",
  ".framer-Pye6k .framer-pan9ol { -webkit-user-select: none; aspect-ratio: 3.675 / 1; gap: 10px; height: var(--framer-aspect-ratio-supported, 40px); overflow: hidden; position: relative; user-select: none; width: 147px; will-change: var(--framer-will-change-filter-override, filter); }",
  '.framer-Pye6k[data-border="true"]::after, .framer-Pye6k [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 88
 * @framerIntrinsicWidth 1140
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameruoXiGtpFK = withCSS(Component, css, "framer-Pye6k");
export default FrameruoXiGtpFK;
FrameruoXiGtpFK.displayName = "Monko Ticker";
FrameruoXiGtpFK.defaultProps = { height: 88, width: 1140 };
addFonts(
  FrameruoXiGtpFK,
  [{ explicitInter: true, fonts: [] }, ...TickerFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FrameruoXiGtpFK",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "88",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "1140",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./uoXiGtpFK.map
